### ISSUE TITLE
Event History

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#11]
Instead of complex QoS for message delivery, provide per-topic configurable persistent message history.

Client can request message history during subscribe or separately:
- last N
- since time T

Events could need an EVENT_ID and/or EVENT_TIME.

Client is responsible to handle overlaps (duplicates) when it wants "exactly-once" message processing.

**Comment by ecorm** [comment]
The spec does not specify the schema for the result of `wamp.topic.history.*`.

**Comment by goeddea** [comment]
Event history is currently one of the unstable features - we haven't quite hashed out the details.

**Comment by dhaowoods** [comment]
Does wamp reinvent the wheel? how complicated it would be if the research effort from university of toronto to be incorporated into WAMP basic profile? [Uniform Querying of Past and Future Events](http://msrg.org/publications/pdf_files/2009/it-0549-The_PADRES_even.pdf)

**Comment by IvaKom** [comment]
Troll?

**Comment by dhaowoods** [comment]
who is troll?

**Comment by goeddea** [comment]
Just had a look at the abstract of the paper you linked to, and what this deals with seems to be outside of the scope of WAMP.

**Comment by oberstet** [comment]
Yes, @goeddea is right.

> This  paper  outlines  requirements  and  sketches techniques

Ah yeah;) Where can I download code?

It's an academic paper presenting "ideas". We are working on actual code used in real applications .,. the IETF mantra: "rough consensus, working code". I like it slick and simple.
