### ISSUE TITLE
Session statechart

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#119]
It would be useful if the spec included statecharts that show the various stages of a session being established. I have sketched my interpretation of the spec in the form of the following statecharts:

![clientsessionstatechart](https://cloud.githubusercontent.com/assets/9258548/5599791/27bc42a8-92a4-11e4-97fa-95a689f6bcba.png)

![routersessionstatechart](https://cloud.githubusercontent.com/assets/9258548/5599792/2dfd5486-92a4-11e4-871d-838499463076.png)

I hereby release these images under the Creative Commons CC-BY-SA license. Feel free to include them into the spec, or use them as inspiration to create your own (prettier) diagrams.

**Comment by oberstet** [comment]
Cool!! I think is is very userful.

From a quick glance (need to finish sth else right now):

* It's missing `ABORT` and the `CHALLENGE` / `AUTHENTICATE` messages.
* Some arcs are probably also missing like for the Router from state `CLOSED`, the only message that's valid to be received is `HELLO` - so there needs to be an arc from `CLOSED` to `FAILED` for any message other than `HELLO`.

I make this into a bug, since I think this definitely should be in the spec.

**Comment by ecorm** [comment]
I updated the statecharts with your suggestions:

![clientsessionstatechart](https://cloud.githubusercontent.com/assets/9258548/5600379/32c69878-92af-11e4-9687-f5cc47a86b8c.png)

![routersessionstatechart](https://cloud.githubusercontent.com/assets/9258548/5600381/37c6b6dc-92af-11e4-9f02-a1b74d03eebd.png)

**Comment by ecorm** [comment]
@oberstet If the client receives an `ABORT` message, should it fail the connection, or go back to the `Closed` state. If the client receives an `ABORT`, can it try establishing a session again during the same transport connection lifetime (perhaps with different HELLO options)?

**Comment by estan** [comment]
I think this is a great initiative that may help implementors.

And look, a question from @ecorm immediately popped up ^ :) Pictures are powerful.

**Comment by meejah** [comment]
@ecorm do you have source for those charts? What did you make them with? (They look good, BTW).

**Comment by meejah** [comment]
@ecorm Since "WAMP sessions" can be established multiple times over the same transport via ``join()/leave()`` I'm pretty certain the abort case would be the same, so yes it can try again over the same transport.

**Comment by ecorm** [comment]
@meejah I used LibreOffice Draw. GitHub won't let me post the original .odg file.

**Comment by estan** [comment]
I can make an SVG version of it if you want, when I get to work in a couple of hours.

**Comment by estan** [comment]
Two questions:

Perhaps the Closing state could be removed and made into a single transition "Received GOODBYE / Send GOODBYE", following the same principle used in other such places? Or is it important to have that transient state explicitly in the chart?

Maybe we could use colors to indicate sent vs received? Would cut down a bit on the text required for each transition. The downside is people with color vision won't like it.. Maybe underline sent messages as well? I'll experiment some.

**Comment by meejah** [comment]
@estan the router is actually "in" the Closing state for some (very brief) but non-zero time as it waits for the Goodbye message to be sent "on the wire" (well, "to the OS" anyway) and for the transport to lose its connection.

**Comment by oberstet** [comment]
As a sidenote, I think state charts could also be useful not only for session, but also for Calls. E.g. since of https://github.com/tavendo/WAMP/issues/160 filed by @ecorm 

A (single) WAMP Call at the router is actually transitioning through states as well ..

**Comment by ecorm** [comment]
> Perhaps the Closing state could be removed and made into a single transition "Received GOODBYE / Send GOODBYE", following the same principle used in other such places? Or is it important to have that transient state explicitly in the chart?

@estan  You're correct that there could be a single `Received GOODBYE / Send GOODBYE` transition from `Established` to `Closed`. I think my motivation for the `Closing` state was an aesthetic one in that `Closing` is somewhat symmetrical to the `Establishing` state. In any case, the important thing about the statechart is that it models the appropriate behavior of a compliant implementation. Actual implementations could deviate from the statechart as long as the external behavior remains the same. For example, some of the actions performed during transitions might also have been modeled as `onEntry` or `onExit` actions.

> Maybe we could use colors to indicate sent vs received? Would cut down a bit on the text required for each transition. The downside is people with color vision won't like it.. Maybe underline sent messages as well? I'll experiment some.

Relying purely on color prevents someone from printing the charts in black and white. The text could be shortened by using "Tx"/"Rx" instead of "Send" and "Received". I think anyone familiar with communication protocols know that Tx and Rx means.

> @estan the router is actually "in" the Closing state for some (very brief) but non-zero time as it waits for the Goodbye message to be sent "on the wire" (well, "to the OS" anyway) and for the transport to lose its connection.

@meejah: The statecharts apply only to the WAMP session layer and assume that a transport has already been connected. After leaving a session, it's possible to rejoin without reconnecting the transport layer (see https://github.com/tavendo/WAMP/blob/master/spec/basic.md#transport-and-session-lifetime). You can think of these statecharts as being part of a `Transport Connected` super state.

You are correct that there is a brief amount of time between receiving `GOODBYE` and the corresponding `GOODBYE` reply being sent. The transient `Closing` state could also be used to show that the implementation rejects all incoming messages at this point.

**Comment by ecorm** [comment]
I'll post a Google drive link to my LibreOffice Draw files the next time I'm in front of my work computer.

**Comment by oberstet** [comment]
@ecorm do you have your design files for the statecharts (LibreOffice Draw) uploaded somewhere? Maybe you could do a PR adding these files to https://github.com/tavendo/WAMP/tree/master/visuals/wamp2 ?

**Comment by ecorm** [comment]
Done. #193

**Comment by oberstet** [comment]
@ecorm awesome! thanks again. I have looked through the client and router state charts, and they are perfectly fine from a first glance. A minor question I had: the router state chart has "challenging" as a separate state, whereas there is no "authenticating" or what state for the client state chart. Is there a specific aspect here?

**Comment by ecorm** [comment]
It's been a long while, but I think my though process what that the client does not need to behave differently after receiving a CHALLENGE message. Thus the reason why it stays in the "Establishing" state.

It wouldn't hurt to have a separate, explicit "Authenticating" state. Such a state would help people visualize how the client state remains in lockstep with the router state during authentication.

Is it possible for the client to receive more than one CHALLENGE message during session establishment? If not, then I think a separate "Authenticating" state would be in order.

**Comment by oberstet** [comment]
@ecorm great! I think a separate "Authenticating" state on the client side would be a good thing (makes it symmetrical or lockstep). btw, I opened this new issue https://github.com/wamp-proto/wamp-proto/issues/194 and will close this one.
