### ISSUE TITLE
Create feature matrix for implementations with WAMP advanced profile

### ISSUE THREAD

**Issue by goeddea** [wamp-proto/wamp-proto#125]
- should include whether a feature is implemented based on the spec, or a vendor-specific or expermiental implementation

**Comment by oberstet** [comment]
We first should fix the list of stable AP features https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#feature-announcement and then use the feature names (exactly as technically used with feature announcement) in the lists as suggested by Emile (https://groups.google.com/d/msg/wampws/NUX4RLt2r6w/8mykg3R4aAIJ)

> We need to think of way to show support for individual features in a compact manner. One observation: _all_ of the implementations currently support the Publisher, Subscribee, Caller, Callee roles, so this information is superfluous and can be removed. That would free up more room for listing advanced features. Perhaps the table should look like this:

>Library | Language | Advanced features
>------- | -------- | -----------------
>CppWAMP | C++11    | RAW

>where RAW is a code representing the raw sockets feature. There could be other features codes listed as well. For implementors that don't report their list of advanced features, you could put a "TBD" (to be determined) placeholder. Below the table, you could have a legend that explains each feature code, with a corresponding link in the specification.

**Comment by ecorm** [comment]
An alternative layout could be:

Library | Language | Caller | Callee | Publisher | Subscriber
--------- | -------------- | --------| --------- | ------------ | --------------
CppWAMP | C++11 | <ul><li>call_timeout</li><li>caller_exclusion</li></ul> | Basic | <ul><li>call_timeout</li><li>publisher_exclusion</li></ul>  | Basic

**Comment by oberstet** [comment]
@ecorm I agree, the table format you suggest is superior. let's go with that

**Comment by oberstet** [comment]
migrated to https://github.com/wamp-proto/wamp-web/issues/15
