### ISSUE TITLE
Web site slidedeck: explain structure before RPC

### ISSUE THREAD

**Issue by Vayel** [wamp-proto/wamp-proto#137]
Currently, the slidedeck on the landing page of WAMP Web site is explaning RPC before introducing to the structure of the ecosystem (various components, communicating through a router). Maybe, it would be more explicit to introduce to that structure before getting interested in RPC and PubSub because it would give a global vision of the ecosystem before learning technical things. Inserting an image like [that one](http://crossbar.io/static/img/gen/web_draft.png), with a few explanations, would do the job.

**Comment by oberstet** [comment]
migrated to https://github.com/wamp-proto/wamp-web/issues/15
