### ISSUE TITLE
What if the Callee does not support CANCEL?

### ISSUE THREAD

**Issue by mbonneau** [wamp-proto/wamp-proto#141]
If a Caller attempts to cancel an RPC where the Callee does not support CANCEL, what should the behavior be?

Should the router send back an error?
Should the router send back the eventual results even though the Caller has requested the cancelation?
What error URI should be sent back to the Caller?

I would suggest:

The router send back `wamp.error.not_supported`.

At that point the call is still not canceled and should behave the same as if the CANCEL was never issued.

This behavior could be overridden by sending an option `CANCEL.Options.discard_results|bool := true` at which point the router will discard the results when they are sent back from the Callee. A `wamp.error.canceled` will be sent back to the Caller.

**Comment by mbonneau** [comment]
Also, should there be a ```wamp.error.no_such_call``` if the requested call doesn't exist?

What should be done if the Callee sends the result after the router sends the INTERRUPT? And what if the Callee only returns the RESULT and never an ERROR?

Would it be better/easier to make a PR with suggested changes to the spec instead of making suggestions in an issue?

**Comment by ecorm** [comment]
> Also, should there be a wamp.error.no_such_call if the requested call doesn't exist?

@mbonneau, there is a `wamp.error.no_such_procedure` URI shown under the [Call ERROR](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#call-error) section, and listed under [Predefined Errors](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#predefined-errors).

**Comment by oberstet** [comment]
related to #159

**Comment by oberstet** [comment]
> If a Caller attempts to cancel an RPC where the Callee does not support CANCEL, what should the behavior be?

Right now I think there are only two options:

* have the cancel fail the call immediately with "call canceled, but callee didn't support canceling", and ignore anything subsequently received from the callee at the dealer already
* have the cancel be ignored and run through the rest of the call as usual (ultimately returning a result, an error from the callee or a call timeout from the dealer)

The behavior might be under control from the canceler via an option.

**Comment by mbonneau** [comment]
I would like to see the default be option 1 (router reports "canceled but callee doesn't support cancel" to the caller and drops the result from the callee) and that could also be controllable by option if supported.

My reasoning would be that a caller may decide that it really doesn't want the result and may not want to consume the added bandwidth if it is going to be a large response sent back.

**Comment by goeddea** [comment]
+1 for going with variant 1. I even think that this should be the only behavior. The caller signals that it doesn't want/need the result by attempting to cancel - so it should not get a result. Why would I want to have logic in my application that deals with a result which I only got because the callee doesn't support call cancellation.

**Comment by gammazero** [comment]
Agree with variant 1:
```
// Check that callee supports call canceling to see if it is alright send INTERRUPT to callee.
// If callee does not support call canceling, then cancel in dealer without sending INTERRUPT to callee.
````

**Comment by KSDaemon** [comment]
I like, what @gammazero said.

**Comment by gammazero** [comment]
Related, and handled by: https://github.com/wamp-proto/wamp-proto/issues/140#issuecomment-364773745

**Comment by oberstet** [comment]
alright, so I think this has reached sufficient consensus: @gammazero has nicely summarized it in https://github.com/wamp-proto/wamp-proto/issues/140#issuecomment-364773745

essentially, the comment can go directly to the spec .. +1
