### ISSUE TITLE
Message flow is not specified in Call Timeouts

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#155]
It's not obvious what the sequence of messages should look like for [Call Timeouts](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#call-timeouts). My guess is that its identical to the sequence shown in [Canceling Calls](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#canceling-calls), with the exception that the caller does not send a `CANCEL` message. In any case, the intended flow should be made explicit for call timeouts.

**Comment by oberstet** [comment]
Yep. Description is lacking.

I once thought that it would make sense to have timeouts originate from a caller, a dealer and a callee. I now think it's the dealer (and only that) which should have a timer running for a call (with timeout option). On a timeout, the dealer would then:

1. send a call error to the caller (with reason "timeout").
2. _if_ the callee supports interrupt, send a INTERRUPT to the callee
3. ignore (throw away) anything that might come back from the callee for that call

**Comment by ecorm** [comment]
> I once thought that it would make sense to have timeouts originate from a caller, a dealer and a callee. I now think it's the dealer (and only that) which should have a timer running for a call (with timeout option).

I guess it comes down to a trade-off between dealer scalability and client complexity. If a client decides to use the `CALL.Options.timeout` option for each and every RPC, then the dealer has to maintain a running timer for every pending RPC from all clients. Wouldn't that scenario hurt performance and scalability on the dealer side?

On the other hand, someone wanting to write a lightweight WAMP implementation for IoT applications might appreciate the built-in dealer-side timeouts feature.

If you leave the normal `CANCEL` mechanism in place, then there's nothing preventing clients from implementing their own "local" timeout mechanism. If you really intend to keep the dealer side timeouts feature, then I think it should not get in the way of clients wanting to implement their own local timeouts.

**Comment by estan** [comment]
Yes, at work we've been starting to think about timeouts, and whether we should do our own local timeouts, or wait for call timeouts to become stable, or use both. It will probably be the latter. We'll have components for (sometimes) wonky hardware and will probably have various places where timeouts come into play.

So please don't remove the cancel mechanism :)

Scalability-wise we'll most probably not have a problem with dealer-side timers, as we don't have a lot of traffic, but I can see this would be a problem in a high-traffic situation if the clients are hammering the dealer with such calls.

**Comment by gammazero** [comment]
I really have not seen a strong use case for dealer timeouts.  If the client no longer cares about a response, then it can issue a CANCEL or just ignore the result if/when it arrives.

Most production systems should have RPC timeouts, and if operating normally will rarely experience a call timeout.  This means that in systems supporting dealer timeouts, the dealer is forced to suffer the overhead of tracking a timer for every RPC call in progress, and that overhead is effectively wasted.  This can even cause performance problems, that would otherwise not occur, during message bursts.

Also, if a client is really concerned about timing out a request, then the client should implement the timeout to handle the case that the router does not respond within the time limit, regardless of what the callee does.  Implementing a timeout to cancel or ignore a response should be a reasonable expectation for even a very simple client.

Therefore, I vote to abolish router-side timeouts completely.  Since:
1. The client should implement the timeout anyway
2. Router-side timeout adds needless overhead and may even cause problems.

No router-side timeout also avoids disagreement in time waited, caused by delays between clients and dealer.

**Comment by oberstet** [comment]
Am 02.09.2018 um 08:38 schrieb Andrew J. Gillis:
> I really have not seen a strong use case for dealer timeouts.  If the client no longer cares about a response, then it can issue a CANCEL or just ignore the result if/when it arrives.
> 
> Most production systems should have RPC timeouts, and if operating normally will rarely experience a call timeout.  This means that in systems supporting dealer timeouts, the dealer is forced to suffer the overhead of tracking a timer for every RPC call in progress, and that overhead is effectively wasted.  This can even cause performance problems, that would otherwise not occur, during message bursts.

yep, agreed, that's an implemention challenge.

eg ABPy (and thus Crossbar.io) has non-trivial code and tuning to make
WebSocket heartbeating work at the scale of millions of connections -
and that involves timers of course

ABPy websocket server is used by Mozilla for FF notifications ..

> 
> Also, if a client is really concerned about timing out a request, then the client should implement the timeout to handle the case that the router does not respond within the time limit, regardless of what the callee does.  Implementing a timeout to cancel or ignore a response should be a reasonable expectation for even a very simple client.
> 
> Therefore, I vote to abolish router-side timeouts completely.  Since:
> 1. The client should implement the timeout anyway
> 2. Router-side timeout adds needless overhead and may even cause problems.
> 
> No router-side timeout also avoids disagreement in time waited, caused by delays between clients and dealer.
> 

IMO router side call timeouts are desirable for 2 reasons:

- it works with any client implementation (which might not implement it,
or not robustly/correctly)

- without it, there is a DoS vector onto the router

-- 
Tobias Oberstein - phone +49 176 2375 2055 - tobias.oberstein@crossbario.com
Crossbar.io GmbH - Waldstrasse 18 - 91054 Erlangen
HRB 15870 - Amtsgericht Fuerth - Geschäftsfuehrer/CEO - Tobias Oberstein

http://crossbario.com

**Comment by ecorm** [comment]
> then the dealer has to maintain a running timer for every pending RPC from all clients. Wouldn't that scenario hurt performance and scalability on the dealer side?

I'm implementing this right now, and it turns out the dealer only needs one timer resource that it updates whenever a new RPC has an earlier timeout deadline.

Dealer-side timeouts are still under-specified. I'm proceeding with them mimicking call cancelling with the `killnowait` mode, which decays to `skip` mode if the callee does not support cancellation. The reason why it's not `kill` mode is that the client has already waited "long enough", and doesn't want to wait any longer for the callee to respond to the cancellation.

Also, there should not be any requirement for the callee to announce the `call_timeouts` feature. The callee only (possibly) sees CANCEL messages and doesn't care if they originated from the caller or dealer. The logic for the callee is the same for call cancellation and dealer-side call timeouts.

The Call Timeouts feature should only be in reference to the dealer running a timeout timer. The following scenarios should be outside the scope of the Call Timeouts feature:
- A caller running its own timer and cancelling an RPC using only the Call Cancelling feature.
- A callee running its own timer and returning an ERROR result if the operation takes too long to complete.

**Comment by ecorm** [comment]
> The following scenarios should be outside the scope of the Call Timeouts feature:
>
>    - A caller running its own timer and cancelling an RPC using only the Call Cancelling feature.
>    - A callee running its own timer and returning an ERROR result if the operation takes too long to complete.

I've re-introduced callee-initiated timeouts into the Call Timeouts features in my PR. Basically, the dealer delegates the timeout logic to the callee.
