### ISSUE TITLE
Clarify use case and details of feature announcement

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#157]
The spec is really confusing with regards to meta events. From what I can infer, there seems to be two mechanisms for meta events.

---

The first mechanism is the **Meta API**, which includes special topics that are "built into" the router.

Documentation on this feature is scattered across the following places:
- `registration_meta_api` and `subscription_meta_api` features URIs listed under [Feature Announcement](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#feature-announcement), but not referenced anywhere else
- A broken _Subscriber Meta API_ link in the table of contents
- A broken _Callee Meta API_ link in the table of contents
- An orphaned [Callee Events](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#callee-events) section not included in the TOC
- A [Predefined Meta Topics](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#predefined-meta-topics) section in the Appendix. Predefined meta topics all have the format: `wamp.*.on_*`.

In addition, there currently exists other undocumented meta events not related to registrations and subscriptions, as raised in https://github.com/tavendo/WAMP/issues/80 and https://github.com/tavendo/WAMP/issues/107.

---

The second mechanism is described in [Subscriber Meta Events](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#subscriber-meta-events). This mechanism relies on the `SUBSCRIBE.Options.metatopics` attribute. It only pertains to meta events related to one particular topic. Metatopics have the format: `wamp.metatopic.<role>.*`

From what I can tell, this mechanism is not currently implemented in Crossbar or Autobahn|Python.

---

The above observations raises the following questions:
1. Am I correct in that there are currently two mechanisms for subscribing to meta events? One via the Meta API, and another via `SUBSCRIBE.Options.metatopics`?
2. The Meta API feature seems to be supported in Crossbar, so should it be considered stable now? I mean stable in the sense that the feature and its usage are stable. The _specification_ of this feature, however, is obviously not stable. :-)
3. Is there really a need for a second meta event mechanism? Wouldn't it be simpler if the [Subscriber Meta Events](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#subscriber-meta-events) feature was implemented in terms of the Meta API? For example, instead of `SUBSCRIBE.Options.metatopics := wamp.metatopic.subscriber.add`, one would use the existing `wamp.topic.on_subscribe` from the Meta API.
4. Should the Meta API be consolidated into its own top-level section, instead of being scattered everywhere?
5. There are only feature URIs for `registration_meta_api` and `subscription_meta_api`. Shouldn't there be more for Session Management and Reflection?

If someone can shed some light on the above questions, I might volunteer to consolidate the Meta API feature into its own top-level section (as proposed in question 4), and submit a PR.

**Comment by oberstet** [comment]
@ecorm I am really sorry for this mess and wasting your time. Actually, a couple of weeks ago, I consolidated most of this (and discussions on the list) and came up with I think a pretty complete meta API in Crossbar.io:

* http://crossbar.io/docs/Session-Metaevents-and-Procedures/
* http://crossbar.io/docs/Subscription-Meta-Events-and-Procedures/
* http://crossbar.io/docs/Registration-Meta-Events-and-Procedures/

There is a complete example here https://github.com/crossbario/crossbarexamples/tree/master/metaapi

This includes a JS frontend to invoke all this stuff.

What I should have done (but failed to do) is update the spec and close all related issues. A PR would be most welcome! I currently just can't keep up with stuff to do ...

**Comment by ecorm** [comment]
The Meta API is mapped to feature announcement attributes as follows:

Feature | Announced In
------ | -----
Subscription Meta Events and Procedures | Details.roles.broker := {subscription_meta_api := true}
Registration Meta Events and Procedures | Details.roles.dealer := {registration_meta_api := true}
Session Meta Events and Procedures | ???

As you can see, there's currently no way to announce support for Session Meta Events. What would be best the way to announce support for such a feature? Session Meta Events doesn't pertain to the _broker_ or _dealer_ roles in particular, but for the _router_ role in general. I can think of the following alternatives:

1. `Details.roles.session := {session_meta_api := true}`
2. `Details.roles.router := {session_meta_api := true}`
3. Both `Details.roles.broker := {session_meta_api := true}` and `Details.roles.dealer := {session_meta_api := true}`

What do you think?

**Comment by ecorm** [comment]
@oberstet , what was the rationale behind the [Subscriber Meta Events](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#subscriber-meta-events) section? Couldn't that feature be implemented in terms in the Meta API? Is it because the Meta API doesn't let you subscribe to `on_subscribe` and `on_unsubscribe` meta events for just one specific pub/sub topic?

**Comment by ecorm** [comment]
I'm working right now on consolidating the Meta API in its own section, while reusing your existing material in the Crossbar docs you cited. I'll be proposing alternate feature announcement tags that won't require us to invent new roles besides "dealer" and "broker". Should be submitting a PR soon.

**Comment by ecorm** [comment]
Submitted PR #179.

**Comment by oberstet** [comment]
Regarding feature announcement of WAMP meta API, this is what we currently use in Crossbar.io: announce `session_meta_api` in both Dealer and Router roles. In addition to `registration_meta_api` and `subscription_meta_api` which is announced in only in the respective role.

This is the client's `HELLO` from AutobahnJS:

```json
[
    1,
    "realm1",
    {
        "roles": {
            "caller": {
                "features": {
                    "caller_identification": true,
                    "progressive_call_results": true
                }
            },
            "callee": {
                "features": {
                    "caller_identification": true,
                    "pattern_based_registration": true,
                    "shared_registration": true,
                    "progressive_call_results": true,
                    "registration_revocation": true
                }
            },
            "publisher": {
                "features": {
                    "publisher_identification": true,
                    "subscriber_blackwhite_listing": true,
                    "publisher_exclusion": true
                }
            },
            "subscriber": {
                "features": {
                    "publisher_identification": true,
                    "pattern_based_subscription": true,
                    "subscription_revocation": true
                }
            }
        }
    }
]
```

and the `WELCOME` message from Crossbar.io

```json
[
    2,
    6043557564026525,
    {
        "authid": "w-QjlnW2WQ6aUC4y61zFTTVZ",
        "authrole": "anonymous",
        "authmethod": "anonymous",
        "roles": {
            "broker": {
                "features": {
                    "publisher_exclusion": true,
                    "subscriber_blackwhite_listing": true,
                    "publisher_identification": true,
                    "pattern_based_subscription": true,
                    "subscription_revocation": true,
                    "session_meta_api": true,
                    "subscription_meta_api": true
                }
            },
            "dealer": {
                "features": {
                    "caller_identification": true,
                    "progressive_call_results": true
                    "shared_registration": true,
                    "pattern_based_registration": true,
                    "registration_revocation": true,
                    "session_meta_api": true,
                    "registration_meta_api": true,
                }
            }
        }
    }
]
```

**Comment by ecorm** [comment]
The "special treatment" given to `session_meta_api` doesn't settle quite well with me, but I don't think it's much of an issue from a practical standpoint.

With the meta API announcement scheme I proposed, the WELCOME message above would have instead looked like this:

```javascript
[,
    6043557564026525,
    {
        "authid": "w-QjlnW2WQ6aUC4y61zFTTVZ",
        "authrole": "anonymous",
        "authmethod": "anonymous",
        "roles": {
            "broker": {
                "features": {
                    "publisher_exclusion": true,
                    "subscriber_blackwhite_listing": true,
                    "publisher_identification": true,
                    "pattern_based_subscription": true,
                    "subscription_revocation": true,
                    "session_meta_events": true, //!
                    "subscription_meta_events": true, //!
                    "registration_meta_events": true //!
                }
            },
            "dealer": {
                "features": {
                    "caller_identification": true,
                    "progressive_call_results": true,
                    "shared_registration": true,
                    "pattern_based_registration": true,
                    "registration_revocation": true,
                    "session_meta_procedures": true, //!
                    "subscription_meta_procedures": true, //!
                    "registration_meta_procedures": true //!
                }
            }
        }
    }
]
```

To me, it seems logical that support for *any* meta-event requires the presence of a Broker. Likewise, support for *any* meta-procedure requires the presence of a Dealer.

Please note that if my proposed meta api announcement scheme ends up being adopted, the current one used by Crossbar would not conflict and could be still used in a deprecated fashion.

I'd like to know which scheme the WAMP community would prefer (or if there's an even better one). Folks, feel free to weigh in on this! :-)

**Comment by jcelliott** [comment]
I personally like @ecorm's proposal here, including the change to the WELCOME message feature announcement.

**Comment by oberstet** [comment]
> Session Meta Events doesn't pertain to the broker or dealer roles in particular, but for the router role in general.
Yes, agree.

> To me, it seems logical that support for any meta-event requires the presence of a Broker. Likewise, support for any meta-procedure requires the presence of a Dealer.
Yes, agree.

We need to conceal above in some way.

Loud thinking:

How could a Dealer provide `dealer.feature.subscription_meta_procedures = true` without there being a Broker?

Dealers **trigger** meta events which need a Broker. And the meta API for a Broker **requires** a Dealer for the meta procedures.

So is `subscription_meta_procedures` a Broker feature because the target of the procedures are Broker internals, or is `subscription_meta_procedures` a Dealer feature because any "procedure" requires a Dealer?

I'd say, `subscription_meta_procedures` is a Broker feature. And the feature can only work if there is also a Dealer. But the Dealer is only a "helper", not the actual originator of the feature.

**Comment by oberstet** [comment]
Continuing this line of thinking:

**Comment by ecorm** [comment]
@oberstet , did you click "Comment and Close" instead of just Comment? Before closing this issue, perhaps we should wait until the feature announcement scheme is settled and that my upcoming Meta API PRs are accepted (or rejected).

**Comment by oberstet** [comment]
@ecorm ah yeah, hit wrong button!

**Comment by ecorm** [comment]
> How could a Dealer provide `dealer.feature.subscription_meta_procedures = true` without there being a Broker?

It shouldn't. Implementation-wise, some higher level entity would have "tell" the Dealer that `subscription_meta_procedures` are available and supported by a Broker being present. The same argument applies to `dealer.feature.session_meta_procedures = true` without session meta-procedures being supported by the Router.

> Dealers trigger meta events which need a Broker. And the meta API for a Broker requires a Dealer for the meta procedures.

> So is `subscription_meta_procedures` a Broker feature because the target of the procedures are Broker internals, or is `subscription_meta_procedures` a Dealer feature because any "procedure" requires a Dealer?

I understand your dilemna. With my proposed scheme, the Dealer role has to be "aware" of subscription meta-procedures, and that subscription stuff is part of the Broker's "domain".

> I'd say, `subscription_meta_procedures` is a Broker feature. And the feature can only work if there is also a Dealer. But the Dealer is only a "helper", not the actual originator of the feature.

The same reasoning could apply to `session_meta_procedures`. It is not a Broker feature per se, but the Dealer is a "helper" and not the originator of this feature.

**Comment by ecorm** [comment]
A third scheme would like the one currently used by Crossbar, but we'd add a "router" role to announce generic features such as `session.meta.api`. But introducing a new "virtual" role might be confusing to people. I'm not particularly fond of this idea.

**Comment by ecorm** [comment]
There are two different issues being discussed here, and it's my fault for separating them. The first is to update the Meta Api spec with what's been implemented so far in Crossbar. The second it how the meta api features should be announced.

@oberstet, is it alright if I proceed with my Meta API PRs, while using the feature announcement scheme **currently** used by Crossbar?

If we end up settling on a different meta api feature announcement scheme, then it'll be another set of changes to be done at later time.

**Comment by oberstet** [comment]
That's right, 2 things being discussed here.

The feature announcement issue is in a way independent of the actual feature definition. So yes, I am fine taking in stuff for feature definition already even if the former isn't hashed out yet.

> add a "router" role to announce generic features

Yep, add a `router` role, or remove the distinction between `broker` and `dealer` roles. And maybe even the client roles, and maybe .. why didn't we just have a single "features" dict?

And ultimately: why do we have feature announcement at all, when it doesn't have any effect? Because we don't talk about consequences of feature announcement: https://github.com/tavendo/WAMP/issues/159

What use case does feature announcement address again?

And if we found the answer to this again, maybe then decisions rgd variants of feature announcement become easier to make.

**Comment by ecorm** [comment]
> What use case does feature announcement address again?

It could be useful when using WAMP services from a 3rd party, where you have no control over the router and its configuration. Otherwise, an application writer should generally know at design time what the router capabilities are.

Since my proposed meta api feature announcement scheme is also not ideal (where brokers have to "know" about dealers, and vice-versa), then I think it's best to stick with the one currently used by Crossbar. Perhaps we should wait for a legitimate use case or bug report to change the current scheme.

**Comment by ecorm** [comment]
Submitted PR #180 for syncing the meta API spec to the one currently used by Crossbar.

**Comment by oberstet** [comment]
The original issue description was touching several things. However, the discussion that unfolded here is mostly about: feature announcement. Changing the issue title to reflect that ..

**Comment by oberstet** [comment]
see also: https://github.com/tavendo/WAMP/issues/159

**Comment by ecorm** [comment]
I think this issue can be closed now. From [the spec](https://wamp-proto.org/wamp_latest_ietf.html#section-10.1-7):

> Support for this feature MUST be announced by both Dealers and Brokers via:
>
> ```
>    HELLO.Details.roles.<role>.features.
>        session_meta_api|bool := true
> ```
