### ISSUE TITLE
Progressive Calls

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#167]
We have "progressive CALL _results_" (https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#progressive-call-results) in the AP.

With this feature, a Callee can produce results in pieces.

It would be consequent and useful in certain situations to allow Callers to issue a call progressively.

That is, send multiple CALL messages with same request ID, with a `CALL.Options.progress|bool := true` option, finalized by a last CALL message with no progress option set.

**Comment by jedesah** [comment]
We have a use case that would greatly benefit from such an addition to the WAMP protocol.

We are implementing a voice search service. Processing voice is fairly slow and in order to minimize the latency experienced by the user of a voice enabled device, it is preferable to start streaming the audio as soon as the user starts speaking as opposed to only once all the audio has been recorded.

An ideal scenario is a WAMP client capable of initiating a progressive call and receiving a progressive result. This way it would be possible to implement a low-latency voice search service that can even return results before the user has done speaking.

**Comment by oberstet** [comment]
Ah, interesting! Yeah, that's probably a good use case for us to verify the feature design.

I guess you will want the progress chunking in Caller->Callee and Callee->Caller directions allowed to be independent? That is, not only have 1 progressive CALL_RESULT exactly per 1 progressive CALL.

**Comment by oberstet** [comment]
Sidenote: we need to make sure this feature works with "shared registrations". E.g. when the same procedure has been registered by multiple Callees, the very first progressive CALL message will make the router select a concrete Callee to forward *this first, and all subsequent CALL messages* to that selected Callee.

**Comment by jedesah** [comment]
@oberstet Yes, being able to independently stream both to and from the client would be ideal.

**Comment by jedesah** [comment]
> to forward this first, and all subsequent CALL messages to that selected Callee.

Yes! This is the most complicated issue I am dealing with implementing my own ad-hoc solution.

**Comment by oberstet** [comment]
Yeah. Actually, in Crossbar.io at least, that's not hard, since we create a proper, stateful call object in the router to correlate messages that come back from the callee to the original call anyway.

**Comment by jedesah** [comment]
Let me know if there is anything I can do to help get this in as fast as possible?

**Comment by konsultaner** [comment]
One of my clients wants to send big files via WebSockets. Increasing the frame size leads into a long blocking of one of the threads in the thread pool. Worst case would be a not reachable server. Progressive calls could solve this issue. Manual chucking would be a reasonable workaround, but I think the protocol could handle it just as well. Especially when it comes to shared registrations.

+1 for this feature

**Comment by cnlpete** [comment]
any news on this?

**Comment by om26er** [comment]
I have a use case for Progressive Calls. I want to send large binaries to a callee and then the callee would do processing on that data. That can essentially be a mixture of Progressive Calls AND Progressive Call results.

The current "hack" that I am thinking is to manually chunk the binary, send that over the wire and in the last message ask for progressive call results.

**Comment by oberstet** [comment]
yes, progressive call arguments should be able to operate together with progressive call results, essentially creating adhoc bidirectional streams. I think there are other places in the issues where this is discussed as well ("streams"), plus there is a sketch of how WAMP IDL could specify such procedures ("stream processors")

https://github.com/wamp-proto/wamp-xbr/blob/eae39f39f8522967752e042c17f5506dd9e9e4dd/work/schema/example1.fbs#L138

to get experiments started, what we would need in autobahn python is sth like:

`Call.Options.progress|bool`: flag that indicates this call argument is a progressive call argument, and subsequent arguments will follow.

in WAMP CALL messages, to indicate. next, the state handling of RPCs in client/server WAMP in autobahn needs adjustment. and then crossbar.

**Comment by KSDaemon** [comment]
Everyone who is interested in this feature, please have a look at #414 PR. 
I described this.

**Comment by KSDaemon** [comment]
Closing via #414

**Comment by ecorm** [comment]
@KSDaemon 
The spec is unclear about receiving progressive results in a progressive call operation. Does the caller need to specify both `progress` and `receive_progress`, or is `receive_progress` automatically implied if `progress` is specified by the caller?

**Comment by KSDaemon** [comment]
Nope, those 2 options are independent. So if you want to make a full-duplex pprogressive call — you must set both.

**Comment by KSDaemon** [comment]
Progressive calls and Progressive call results are two separate independent features that are described in separate chapters of the spec. Mb it is a good idea to add a paragraph about using them both at one time. 

Where should this be added? Adding another chapter just for this purpose does not fit the overall structure and seems unnecessary. Add a similar paragraph to each feature?

**Comment by ecorm** [comment]
> Mb it is a good idea to add a paragraph about using them both at one time.
> Add a similar paragraph to each feature?

I think adding a paragraph under Progressive Calls would be sufficient.

There is already this [example](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-15) which combines the two. This is what led to my confusion about `receive_progress` being implied if `progress` is specified.

I also noticed this [paragraph](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-9) is a bit ambiguous:

> Cases when Caller sends CALL message with progress := true to Dealer, that did not announce progressive calls support during WELCOME handshake MUST be treated as PROTOCOL ERRORS and underlying WAMP connections must be aborted with wamp.error.protocol_violation error reason.

I would suggest this instead:

> In cases where the Caller sends a CALL message with progress := true to the Dealer**, the latter not announcing** progressive calls support during WELCOME handshake, MUST be treated as PROTOCOL ERRORS and underlying WAMP connections must be aborted with wamp.error.protocol_violation error reason.

Also, there is no clause that specifies that the callee must support call canceling.

Would you like me to submit a PR?

**Comment by KSDaemon** [comment]
Your PR would be great!

> Also, there is no clause that specifies that the callee must support call canceling.
Call canceling feature is  mandatory only for `progressive call results` and not for progressive calls. That is Why it is omitted I suppose.

**Comment by ecorm** [comment]
> Call canceling feature is  mandatory only for progressive call results and not for progressive calls. That is Why it is omitted I suppose.

But the [Progressive Call Cancellation](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-32) subsection mandates that `INTERRUPT` be sent to the callee when the original caller is no longer available. The `call_cancelling` feature flag is the only way to know if the callee supports `INTERRUPT` messages.

**Comment by KSDaemon** [comment]
Ah! Yeah! You're right! I forget about that! My bad!

**Comment by ecorm** [comment]
See PR #445
