### ISSUE TITLE
Compararison with Vert.x

### ISSUE THREAD

**Issue by Vayel** [wamp-proto/wamp-proto#168]
It would be judicious to add [Vert.x](http://vertx.io/) in [that list](http://wamp.ws/compared/), wouldn't it?

**Comment by oberstet** [comment]
In general, yes. While Vert.x isn't a protocol, and hence it can't be compared to WAMP in a strict sense, a comparison might be interesting to developers nevertheless. Probably a comparison to Crossbar.io would be more "apples to apples".

**Comment by oberstet** [comment]
migrated to https://github.com/wamp-proto/wamp-web/issues/15
