### ISSUE TITLE
List client implementations by language

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#177]
Users often want to look up WAMP implementations by the language they use, like so

| language (run-time) | implementations |
| --- | --- |
| **Python** | [AutobahnPython](http://autobahn.ws/python) provides a WAMP client library with support for many features from the WAMP AP. It runs on Python 2 and 3, on top of Twisted or asyncio. |
| **Java** | [jawampa]() |
| **C#** | [WAMPSharp]() |
| **JavaScript** | [AutobahnJS](http://autobahn.ws/js). Runs in browsers and NodeJS. |
| **PHP** | [PHP](https://github.com/voryx/Thruway) |
| **ObjectiveC (iOS)** | [MDWamp](https://github.com/mogui/MDWamp) |

We should reformat the implementations page to reflect that.

**Comment by konsultaner** [comment]
do you also accept a commercial implementation for the listing or only free ones?

**Comment by oberstet** [comment]
@konsultaner To be honest, you are the first to ask;) I think there is at least one closed-source C WAMP, but it's built into an embedded device. All others implementations I am aware of are open-source. But I don't see a reason why we should deny it. The WAMP web site is all about a neutral, community place for WAMP users and developers. And if it's useful for WAMP users to know about your implementation, that's good reason. So yes.

**Comment by oberstet** [comment]
migrated to https://github.com/wamp-proto/wamp-web/issues/15
