### ISSUE TITLE
Jabber-RPC

### ISSUE THREAD

**Issue by flosse** [wamp-proto/wamp-proto#187]
On http://wamp.ws/compared/ it looks like XMPP has no RPC support but as far a I know [Jabber-RPC](http://xmpp.org/extensions/xep-0009.html) exits since 2001. What do you think about it?

**Comment by oberstet** [comment]
a) Jabber-RPC is an _extension_ to XMPP
b) it does not provide _routed_ RPCs

I agree that it would make sense to discuss this in more detail on http://wamp.ws/compared/#xmpp

**Comment by flosse** [comment]
> a) Jabber-RPC is an extension to XMPP

well, the nature of XMPP is the extendability ;-)

> b) it does not provide routed RPCs

yes, but this is a separate column on the website.

> I agree that it would make sense to discuss this in more detail on http://wamp.ws/compared/#xmpp

that would be great :)

**Comment by oberstet** [comment]
> well, the nature of XMPP is the extendability ;-)

As is TCP. The point is: it is not built in. You have to layer more stuff on top.

**Comment by oberstet** [comment]
migrated to https://github.com/wamp-proto/wamp-web/issues/15
