### ISSUE TITLE
Integrate state digrams into rfc draft

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#194]
* Add "authenticating" state to client state diagram
* Transfer the state charts into ascii for rfc

* https://github.com/wamp-proto/wamp-web/blob/master/visuals/wamp2/client_session_state_chart.odg
* https://github.com/wamp-proto/wamp-web/blob/master/visuals/wamp2/router_session_state_chart.odg

**Comment by oberstet** [comment]
@ecorm https://github.com/wamp-proto/wamp-proto/blob/master/rfc/diagrams/peer_statechart.txt

**Comment by ecorm** [comment]
@oberstet Nice! The use of parenthesized number callouts make sense, since the transition text would clutter up the ASCII diagram too much.

Did you know there are online ASCII block diagram editors? I hope you didn't "draw" that by hand! :-)

**Comment by oberstet** [comment]
I used http://asciiflow.com/ to "draw" .. works remarkably well and quick. And yes, the structure of the client/router state machines is the same, but the transitions will take/produce different messages. This is interesting, as I didn't start from state machine diagrams when writing code .. I am pretty sure once I start comparing the state machine with the code, that I might find potential to improve the code;)
