### ISSUE TITLE
Contribution and Submission Guides

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#198]
lets steal some guides from here:

* https://github.com/http2/http2-spec/blob/master/CONTRIBUTING.md
* https://github.com/http2/http2-spec/blob/master/SUBMITTING.md
* https://github.com/http2/http2-spec/blob/master/README.md

**Comment by goeddea** [comment]
We have both now:

* Contributing: https://github.com/wamp-proto/wamp-proto/blob/master/CONTRIBUTING.md
* Submitting: https://github.com/wamp-proto/wamp-proto/blob/master/SUBMITTING.md
