### ISSUE TITLE
current subscription meta-events rely on common subscription ID for a topic

### ISSUE THREAD

**Issue by goeddea** [wamp-proto/wamp-proto#201]
The basic spec leaves it up to the broker how it assigns subscription IDs.

With the meta-events, when it e.g. says that `wamp.subscription.on_subscribe` has the 'ID of the subscription to which the session is being added' as an event argument, then this only makes sense if the broker assigns a common subscription ID to multiple subscribers (really: all subscribers).

Otherwise we'd need a topic URI in there.

**Comment by oberstet** [comment]
No, because you can get the details of a subscription using ID only by querying other meta API.
