### ISSUE TITLE
Event history and black/whitelisting by ID = disclosure of events

### ISSUE THREAD

**Issue by bwegh** [wamp-proto/wamp-proto#206]
I think the following is an issue:
User A connects to router and gets the ID 123,
a Publisher publishes an event E with excluding the ID 123,
So A does not receive the event.

User A reconnects and gets the ID 124 and 
asks for the event history an gets the Previous event E,
as only ID 123 is blacklisted.

I know this works with user/roles but doing this with IDs is a security hole in my opinion.

So maybe black/white-listing by ID should be deprecated or dropped in RFC.

**Comment by oberstet** [comment]
Event history isn't defined (completely) right now.

> So maybe black/white-listing by ID should be deprecated or dropped in RFC.

No

**Comment by oberstet** [comment]
I have thought about this a little.

The session ID is ephemeral, and looses any meaning when the session has closed.

I think the main use case for bw-listing based on session ID is to exclude a caller from receiving events the procedure being called produces. At least that's how I use it most often.

This use case is not about security, more about side effects between code. But it's a use case.

I think you are right that using session ID based bw-listing can be a security issue in the situation you describe. But I think the solution is not to drop session ID based bw-listing, but have the event history store the black-/whitelisting information along with the event. Using this info, the bw-listing can be reapplied when retrieving history.

**Comment by bwegh** [comment]
I understand your use case, what I do is just return an "ok" to the caller and let everyone process the events, including the caller. This way I know that even the information presented at the caller made the same round trip through the router as for all other subscribers.
So in my opinion there is no need for bw-listing for this use case.

I assume storing of the bw-listing with the event. 
yet, as you mentioned, reconnecting usually gives a new session id.
So there are two problems:
1. A bad user B who is on the black lists and reconnects to read the event history (as he has a new session ID he will get them)
2. A good user G who is on the white list, the connection fails somehow. She reconnect and does not get the events as her new session id is not on the white list.

So the combination of bw-listing on session ids with event history does not make sense to me.

**Comment by oberstet** [comment]
> So the combination of bw-listing on session ids with event history does not make sense to me.

Yes. But that doesn't mean either feature on it's own is pointless.

Anyway: we won't remove session ID based bw-listing.

**Comment by bwegh** [comment]
It should be in the documentation of both, bw-listing and event history stated that bw-listing based on IDs MUST NOT be stored in the event-history.

In contrast to bw-listing on role or user, as they both MUST be stored in the event-history.
These stored bw-listings MUST also be applied on a request to the event-history.

So making this point clear in the documentation, maybe even mentioning them in the security considerations for both.

**Comment by goeddea** [comment]
I see the issue. The main use case we have for the bw-listing is that in a UI changes to data made externally may be handled differently than local ones. We found it the most straight-forward solution to exclude a caller from a publish made based on the call. This way things can be handled without having any extra information in the publish which would only be used by the caller to make the distinction. 
For the above use case, event history based on sessionID is not a problem. It does become one when the bw-listing is used to exclude users from receiving information instead of just clients.

**Comment by bwegh** [comment]
yes, exactly that is the issue, @goeddea

**Comment by oberstet** [comment]
So we need to work out the semantics when combining features:

* bw listing (based on session IDs, auth IDs and authroles)
* event history
* session resumption https://github.com/wamp-proto/wamp-proto/pull/264

> Rgd session resumption: in this case, a reconnecting, resuming client will get the _same_ session ID as before.

**Comment by gammazero** [comment]
When designing the feature, consider the Issue #291 .  Should be same as authid and authrole handling.

**Comment by oberstet** [comment]
yep, since bw listing was indeed expanded for authid and authrole, I agree, we have to define the behavior wrt to those as well.
