### ISSUE TITLE
As Webrtc signaler

### ISSUE THREAD

**Issue by KrishnaPG** [wamp-proto/wamp-proto#207]
Not sure if this one goes here or into the crossbar.io, but to be able to lead IOT space , supporting P2P style of operations is must for IOT Version 2. MQTT is doing good for now, as academic exercise - but will not last for long without P2P support. ZMQ excels at p2p (brokerless), but is geared towards throughput and not concurrency. (And security is another problem with it).

Where autobahn (wamp??) excels is, it has polyglot ability like ZMQ, security of WSS, and RPC capability.  

One major advantage for WAMP over MQTT (at the pure pub-sub level) is: its http compatibility. MQTT lacks on that one big time, with its custom broker / protocol requirements.

ZMQ can do RPC with ease, but RPC over http (say, in browser) is something it lacks.

So, all in all, WAMP looks like it has got all for us to be used for our M2M servers, except for one thing: it is brokered (mandatorily).

In our cases of M2M devices connected over dynamic P2P fashion on road exchanging traffic information, or household devices within a compound connected over wifi exchanging media information, connection brokering becomes a big dance (and costly one for servers **as well as** clients).

WebRTC is one that is very close to addressing this, and where it lacks (for good) is - it still requires a "signaler" to establish the initial P2P connection. This is where WAMP could step-in. 

From my tests, it looks like WAMP (autobahn/crossbar?) has the ability to detect the peers upon session initialization with meta events. 

Making WAMP as "WebRTC signaler compatible" (which means, webrtc clients, which are essentially browsers, use WAMP servers to lookup the peers using the WebRTC protocol and then connect to the peers directly using WebRTC), then it solves many problems for the future IOT apps. (something like what [peer.js](http://peerjs.com/) does)

People are already trying/using WebRTC with socket.io (e.g. [here](http://stackoverflow.com/questions/30975832/using-webrtc-with-socket-io)), so I believe WAMP is not far. For all that I know, may be it is even ready in its present state to be used as WebRTC signaler, and all that is needed is a good example on how to do it !!

Thanks for your time in looking into this.

**Comment by oberstet** [comment]
WAMP is a routed protocol by design for various reasons. We won't change that.

For signaling in WebRTC, you can use WAMP, and the fact that WAMP is a routed protocol is of no relevan.ce
