### ISSUE TITLE
Publisher Exclusion subsections at wrong level

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#208]
The "Feature Definition" and "Feature Announcement" subsections under [Publisher Exclusion](https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-13.4.2) are level 2 headings. They should be level 5 headings.

**Comment by ecorm** [comment]
I would fix this myself and submit a PR, it's just that I don't know how you get the heading levels set-up properly from within the markdown page.

**Comment by goeddea** [comment]
Thanks for pointing this out. Is fixed and will be in next release.
