### ISSUE TITLE
WAMP v1 protocol documentation

### ISSUE THREAD

**Issue by k-vladyslav** [wamp-proto/wamp-proto#210]
Hi @goeddea. Where I can find documentation regarding to WAMP v1 protocol. Im using http://autobahn.ws/js/reference_wampv1.html and I need to conduct some stress/volume testing. For that I need to understand how protocol of v1 works and how are websocket frames being formed.

**Comment by oberstet** [comment]
WAMP v1 is deprecated for long time now, and the spec isn't online anymore. Curious, why do you want/have to use WAMP v1?

That being said: you can dig out the old spec from this repo of course, e.g. [here](https://github.com/wamp-proto/wamp-proto/blob/115f7bada4d784af40e820203f84f6e968e873cc/website/wampws/templates/page_t_spec_wamp1.html). You could also checkout the repo at that version and build the web site from this to get a more readable, rendered HTML output.

@goeddea we should remove the docs in AutobahnJS for WAMP1 .. this: http://autobahn.ws/js/reference_wampv1.html, and update other doc pages in AutobahnJS removing all references to WAMP v1

**Comment by oberstet** [comment]
migrated to https://github.com/crossbario/autobahn-js/issues/166

**Comment by k-vladyslav** [comment]
@oberstet thank You for response, I've structured my answer by topics

1. Why I want to use WAMP v1: I suggest to use WAMP v1 in pair with Ratchet (http://socketo.me). Here http://socketo.me/docs/push you can find demo example which is bound to WAMP v1. It didn't work with latest Autobahn.JS which is implement as WAMP v2 client.

2. Is Ratchet supports WAMP v2? No, it does not. You can take a look at this https://github.com/ratchetphp/Ratchet/issues/168#issuecomment-55339203 answer, You have also participated in that discussion a year ago.

3. @goeddea please do not remove documentation for legacy AutobahnJS, as there might be people across globe (like me) who use servers (like Ratchet) which does not support WAMP v1.

4. Why not to use Thruway (https://github.com/voryx/Thruway)? Because of
* I don't see any chance to integrate communication with RabbitMQ (brokerage we using) through STOMP protocol https://www.rabbitmq.com/stomp.html. Any example?
* On the other hand Ratchet has ready-to-use solution for that https://github.com/reactphp/stomp
* Thruway has weaker documentation and smaller community, but this is imho.

**Comment by davidwdan** [comment]
@k-vladyslav in general, anything that works with Ratchet, will also work with Thruway.  It's not a drop in replacement because WAMP v1 and v2 are pretty different, but it's built on the same libs (Ratchet and React).
