### ISSUE TITLE
My thoughts

### ISSUE THREAD

**Issue by lordnynex** [wamp-proto/wamp-proto#211]
Hello,

Upfront, my apologies for the loose and informal GH issue. I spent the evening implementing wamp and I wanted to share some of my thoughts. Sorry, it's gonna be long.

There seems to be some generalized deep thinking in the RFC around ID generation, but I've come to the conclusion it's troublesome in it's current state. In my particular use case, I am using autobahnJS and a proprietary Lua (luajit) implementation embedded into nginx. 

The root of the issue is the potential for extremely large integer generation for ID's. In my case, lua does indeed support doubles, but not all things in it's ecosystem handles them appropriately. Upon exploring the issue further, I've come to the larger realization that data serialization varies between frameworks in often very subtle ways. 

One issue is the potential for session state trainwrecks caused by serializers and languages that add a signifcand (scientific notation) to large integers. Currently, (as far as I can tell) the protocol does not provide a means to dictate valid integer ranges to clients and thus has to incur serialization overhead for whatever the client decides to send. Expressing these large numbers appears to be supported by the JSON RFC but it expects these values to be formatted in a very specific way. Most serializers don't seem to implement this notation. In my google searches I've found many bugs that were fixed by adjusting PHP's float precision. This may be an acceptable change for PHP but in my case json serialization is outsources (a'la FFI) to a C library that only supports 14 digit precision. I believe this is 1 or 2 digits short of the specifications upper range. For the time being, I am monkey patching my client implementations to limit the upper bound for ID generation. This is fine for my use case, but makes my services completely incompatible with public client libraries. 

Another issue is the processing overhead for such large integers. This issue is less apparent in most implementations I've seen. Incurring a time cost for blocking operation to deserialize messages is not so noticeable in multi-process architectures but significantly breaks down in some single threaded applications. Under the covers, websockets are a tight socket_recv loop. If a blocking operation happens in the deserialization phase the entire loop breaks down. In my case, this disrupts the receive loop of all connected clients. This adds a burden to server side developers who may be using FFI interfaces to blocking serialization libraries (in my case cjson). The obvious fix is to use a serializer that is capable of yielding but I find it troublesome that it's so easy to shoot myself in the foot in such a non-obvious way. I would expect a similar hang in a server side implementation that uses something like python twisted and an FFI bound cjson serializer. While it may not hang, I would expect the service to become latent and not scale well. 

There also seems to be a potential for sequence ID collisions. I may have missed a part of the spec that addresses this but it seems to naively assume everyone is seeding their random number generators appropriately. There is no means for the server to validate that an ID was generated properly. It would be trivial to write a client that generates and sends many poorly formed ID's. (In the case of JIT or similar compiled languages rand() can be quite dangerous). I have not explored the security implications of such a situation. 

Off the top of my head, here are a few possible solutions
- Relax type enforcement of ID's. Allowing ID's to be represented as strings will remove the serialization burden associated with large integers. This will have some side effects. Services that store these ID's will incur additional storage overhead.
- Lower the upper bound for ID generation to a value that is 'more likely' to be supported by serializers in their default configuration. In my use case, that is 14 decimal places. I think this is a bad approach. 
- Change ID generation entirely! 

After only thinking about this for about 12 hours (read: it may be half baked) I think a strong solution is to borrow ObjectID generation from mongodb/BSON. You can read more about what goes into an ObjectID at https://docs.mongodb.org/manual/reference/object-id/ 

OID's would offer the following benefits
- Widely understood and implemented across many languages. I generally use javascript implementations as a litmus test for portability in these situations. One such implementation that I like is https://github.com/williamkapke/bson-objectid/blob/master/objectid.js
- Much greater uniqueness with very little processing overhead. These values are actually used as guaranteed unique values in extremely high traffic DBs. 
- Well suited for both binary and string transports. (as a hex value or binary number) As I write this, I think it may be valid to pass these values as a hex literal which would not require allowing string type ID's in the protocol. I'd have to research this further. 
- Offers the ability to validate the message is formed properly! Currently, the implementation only seems to care if the ID is an integer of some sort. A small example would be the ability to regex test() the ID to ensure it's valid before even parsing it to determine whether the message is valid. 
- Offers some security mechanisms to validate session state by inspecting various components of the ID for that session. See next:
- Limited ability to observe network/processing latency without reading data from the raw TCP packet. If part of the ID indicates a UTC timestamp, you can begin to sample RPC processing time by diff'ing the message ID's timestamp against the time() you received the response from the service. In this way, a developer would be able to make intelligent decisions about routing requests to route around a degraded service entirely! That is a truly compelling benefit in my eyes. 

I've rambled on long enough. I hope I've made a compelling case for amending the next version of the protocol specification. 

PS, I would LOVE to see the addition BSON as possible message format for binary transports.

**Comment by oberstet** [comment]
Thanks a lot for your detailed feedback, description of your issues and suggestions!

First, it's important to recognize that WAMP uses IDs with 3 different scopes: https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#page-14

Let's take **request IDs**. Those are integers that SHOULD be incremented from 0 upwards and wrap around at 2**53.

The reason for 2**53 is: this is the largest integer that can be represented in IEEE double so that all smaller integers can be represented as well.

E.g. JavaScript uses doubles as it's number type. As does Lua, right?

But you say: the problem is when serializing a double, because some serializers will cut off decimal places?

Python:

```console
oberstet@thinkpad-t430s:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 2**53
9007199254740992
>>> import json
>>> json.dumps(2**53)
'9007199254740992'
>>> 
```

JS:

```console
oberstet@thinkpad-t430s:~$ node --version
v0.10.25
oberstet@thinkpad-t430s:~$ node
> JSON.stringify(9007199254740992)
'9007199254740992'
> 
```

What does you Lua implementation return on above?

**Comment by oberstet** [comment]
> PS, I would LOVE to see the addition BSON as possible message format for binary transports.

Why?

Is there any advantage of BSON over MsgPack?
