### ISSUE TITLE
Multiple WAMP Sessions per Transport Connection

### ISSUE THREAD

**Issue by hugomallet** [wamp-proto/wamp-proto#215]
Hello,

I would like to know (it is not clearly defined in the specification) if a connection could have multiple WAMP sessions.

In my case, i have one client which is a proxy between the WAMP Router and WAMP Clients:

![wamp-proxy](https://cloud.githubusercontent.com/assets/1888705/11032843/024786ba-86df-11e5-8163-15db82a7180b.png)

The proxy hosts a map between RegistrationID/SubscribeID/SessionID and transport connections in order to relays messages. Also it listens for connection close event and sends GOODBYE message on the other side.

Some WAMP implementations attach directly a WAMP Session to a transport session. So my question is: 
Is it expected that an implementation supports multiple WAMP Sessions per transport session?
Or is this architecture compatible as it is with the WAMP protocol?

**Comment by meejah** [comment]
It is currently possible to keep a single transport alive and have a WAMP sessions ``join`` and ``leave`` multiple times on that one transport without tearing it down. However, that is either 0 or 1 WAMP sessions, not multiple sessions at one time.

So: I think your architecture is fine, so long as you don't tie the transport and WAMP session lifetimes together. If the transport dies, of course the WAMP session on it dies too but not necessarily vice-versa...

Also: the spec should probably make this clear. There used to be a lifecycle diagram somewhere. I think both section 7 (Sessions) and 5.3 (Transports) could use a sentence or two clarifying this fact.

**Comment by oberstet** [comment]
As of today, the situation is this:

1. a WAMP session cannot live longer than the underlying transport
2. there is no multiplexing WAMP transport defined

Rgd 1: This would be relaxed by session freeze/resume (session resumption)
Rgd 2: This would be defined not at the WAMP level, but at the transport level: https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/advanced/ap_transport_multiplexed.md
