### ISSUE TITLE
invocation policy change handling

### ISSUE THREAD

**Issue by konsultaner** [wamp-proto/wamp-proto#219]
I have build a complete working WAMP Router. While using it in in production I realized that the invocation poilcy handling leaves a question open to me. The definition says that the first client that registers a procedure is to choose the invocation policy (round robbin, first last, random). Does this also mean that if all clients have unregistered and for some reason a new client comes up again, this new client is treated as a nth one or a new first one? The question could also be: Can a System change the policy by unregistering all clients and then have a new first client?

**Comment by oberstet** [comment]
Good question.

Crossbar.io behavior: when all callees on a registration have left, the registration inside the router is deleted completely, and a new client can register with a different policy.

I think this behavior makes sense. But, we might run into issues with "session freeze/resume". When a client session ends ungracefully, and the router implements resumable session, the session might come back .. so we can't allow the registration to disappear completely yet, and hence the policy cannot change until **all callee session have ended, _and_ none can't be resumed**.

**Comment by konsultaner** [comment]
I currently keep the registration state no matter what. But I have no idea what side effacts may appear. The only problem I came accross, is that I need to restart the router if I wanted to change a policy, which was enoying.

**Comment by konsultaner** [comment]
The [registration_meta_api](https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/advanced/ap_rpc_registration_meta_api.md) actually kind of answers this question. Since you need to delete the registration, all belonging information usually get deleted too.
