### ISSUE TITLE
Building fail-over routers cluster

### ISSUE THREAD

**Issue by barbushin** [wamp-proto/wamp-proto#236]
As far as I can see in WAMP specs, it's designed with only one possible router-server that makes infrastructure based on WAMP not 100% high-load & fail-over stable.

For example: you can't setup multiple router servers with some balancer because there is no `router <--> router` requests proxying.

Is it possible to specify something for routers scaling?

... discussion about this issue started at https://github.com/voryx/Thruway/issues/175#issuecomment-183202336

**Comment by konsultaner** [comment]
this is [out of the wamp specs scope](https://github.com/wamp-proto/wamp-proto/issues/235) as far as I can tell. But I started a [stackoverflow](http://stackoverflow.com/questions/35316766/wamp-protocol-scaling-out-routers-on-multiple-machines) discussion about that topic.

**Comment by oberstet** [comment]
Yes, production environments often will have the need to run a WAMP router that provides HA and scale-out features.

However, such features are out-of-scope wrt the WAMP spec and protocol itself: https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/basic/bp_intro_design_philosophy.md#router-implementation-specifics

As this issue hence is out-of-scope, I am closing this .. sorry, please understand. However, for Crossbar.io, the best way to join in would be a post on https://groups.google.com/forum/#!forum/crossbario describing your use case, requirements and expectations first.
