### ISSUE TITLE
Is there a reason not to allow subscribe to have arguments?

### ISSUE THREAD

**Issue by fresheneesz** [wamp-proto/wamp-proto#237]
I can imagine there being cases where a subscription might need variable information, and putting that in some kind of string-based format separated by dots seems unnecessarily cumbersome. Why not allow arbitrary arguments just like you would pass into `call`?

**Comment by ecorm** [comment]
@fresheneesz It's the *addition* of features that should require a reason, not the absence of a feature. Please provide a legitimate use case for this proposed feature.

What do you propose that the broker (router) do with these arguments?

**Comment by fresheneesz** [comment]
@ecorm You're absolutely right. But it seems to me that WAMP's definition of pub/sub isn't much different from the RPC spec. All you're doing when you subscribe is calling an endpoint on the server that may trigger an endpoint on the client at some point. You could easily do that by using call in place of publish, and register in place of subscribe. 

What I would propose the broker do with the arguments is use them to figure out what to subscribe the user to. This isn't an extra feature as much as it is an alternative features. With arbitrary arguments you do away with any need for fancy wildcard subscriptions and other features that can only cover some use cases. Arbitrary arguments cover all use cases. 

Lets say you have some vehicle subscriptions. You have your make/model/year format for vehicles so you could `subscribe("acura.integra.1987",callback)`, but you also want to be able to subscribe to all red vehicles, or all red motorcycles, or all red motorcycles made in 1992. It would be a pain in the ass to have to do all that with a string like "vehicles.color-red.type-motorcycle.date-1992". And obviously wildcard conditions don't cover this case. 

What would be better is if you could say `subscribe("vehicles", {color:'red',type:'motorcycle',date:1992}, callback)`. 

Perhaps I don't understand the importance of the broker and dealer to communication, but it seems to me that the concept of a broker and dealer should be a separate protocol that runs on top of WAMP - not part of WAMP itself. It seems to me that broker and dealer help with the logic of how and where the calls are executed rather than being at all related to communication between two peers.

**Comment by Paranaix** [comment]
This seems interessting. We currently built alot of code on top of Autobahn just to deal with such scenarious in a simple, consistent and non-errorprone way. This could make that code obsolete. Directly working with keyword arguments instead with a string you firstly have to assemble seems much more elegant.

**Comment by oberstet** [comment]
> the concept of a broker and dealer should be a separate protocol that runs on top of WAMP

No. This would remove all interesting semantics from WAMP.

What you seem to have in mind is usually called "content based subscriptions" - the broker will distribute events based on application payload / content.

WAMP (deliberately) does not support that.

> Is there a reason not to allow subscribe to have arguments?

Yes: WAMP does not support content based subscriptions.

**Comment by fresheneesz** [comment]
> This would remove all interesting semantics from WAMP.

You don't find RPC and event semantics interesting by themselves? 

> WAMP (deliberately) does not support [content based subscriptions].

Would you mind pointing me towards a discussion about why WAMP doesn't support that, or lacking that, explaining to me why not?

To my mind, a messaging protocol shouldn't be opinionated about what kinds of messages are being passed. The whole point of a protocol like this is to do the mundane stuff for you so you can write the interesting stuff unencumbered. If the system itself encumbers you, a lot of the usefulness of the system is lost.

**Comment by oberstet** [comment]
> To my mind, a messaging protocol shouldn't be opinionated about what kinds of messages are being passed.

Sure, and hence WAMP supports very flexible app payloads via `args` and `kwargs`.

But WAMP strictly follows this principle: routing and app / domain specific code MUST be separated. Allowing content-based routing ("if order_amount > 100 then route call to X else Y") is breaking this principle.

> Would you mind pointing me towards a discussion about why WAMP doesn't support that

Probably it's early on in the mailing list. Otherwise, the principle of decoupling, and strict separation of routing and domain code is a principle I came up with while designing WAMP initially. It's a core design principle, and giving up on that would IMO be a deadly mistake.

The ESB (and SOA) made that mistake: putting domain smartness into the coms infra - a mistake. WAMP follows microservice philosophy: dumb pipes, and smart endpoints (where "dumb/smart" refers to domain logic, not necessarily coms infra).
