### ISSUE TITLE
More informations for wamp.session.on_leave

### ISSUE THREAD

**Issue by sehoffmann** [wamp-proto/wamp-proto#238]
Currently `wamp.session.on_leave` only receives the session id as sole argument. This imposes a problem, as a subscribee has no way to acquire additional informations he might be interested in like, authid, role or the realm left.

But wait, isn't there `wamp.session.get` you might ask now. Indeed there is, but the current draft makes no assertions about whether the session information can still be queried in `wamp.session.on_leave` and the standard implementation crossbar will currently let you down in that regard and correctly tells you, that he doesn't have such a session, as it has already been left.

**Comment by oberstet** [comment]
Yes, I agree with all of your description, and yeah, it's bad.

It's probably worth mentioning that `wamp.session.on_leave` should probably get not only the `sessionid`, but also `authid` and `authrole` of the leaving (or left? see below) session. We could add that as keyword arguments to the user hook, and that would make it backwards compatible. The `sessionid` would continue being delivered as a positional argument.

Now, is the session "still there" when `wamp.session.on_leave` fires and presumably then can be queried using `wamp.session.get`? As soon as one WAMP peer starts a closing handshake, the session will no longer process WAMP messages other than required for the closing handshake. The session information is currently garbage collected when the WAMP session ends, but the information tracked about a session could continue to exist after the session ends. That would be useful, definitely.

**Comment by meejah** [comment]
To mirror on_join more closely, maybe it just gets a "details" arg that is a dict with all the things that the on_join details has in it? Obviously, this would need to be a second positional arg (or "details=" kwarg) for backwards compatibility ... 

As to persisting the data: this could get tricky. For how long shall session data be persisted? etc. Basically, you can't really be sure that the session data is around when ``on_leave`` is run by the client since it could be an arbitrary amount of time in the future -- in *practice* a few seconds would probably suffice, but ... maybe it's best to simply declare that ``wamp.session.get`` is *not* guaranteed to be available by the time the subscriber is processing ``on_leave`` (so clients have to "make do" with the details).

This kind of just leaves it up to the router, I suppose: so a router implementation could choose to persist session-data for a configurable amount of time. I can't think of any way to persist the data for the "correct" amount of time -- e.g. you'd need something like a "yes I'm done doing on_leave for session_id" message from each client (but then what if the client runs into errors/goes away/forgets to ack?)

**Comment by goeddea** [comment]
Agree that this is presently a problem. My assumption is that a client subscribed to "on_leave" could use all information available about the session, and should receive this (so I agree with @meejah that this should mirror "on_join"). I further agree that while a few seconds of keeping the information and allowing it to be retrieved via `wamp.session.get` would cover most use cases, guaranteeing persistence beyond that is problematic. It appears cleaner to just send the information with `on_leave`.

**Comment by oberstet** [comment]
If we send all info in `wamp.session.on_leave`, then why call `wamp.session.get` in the leave handler anyway?

**Comment by goeddea** [comment]
In this case there would be no need to call `wamp.session.get` in the handler. This would solve the question of how long to persist the session information (it can be discarded immediately once all subscribers to `on_leave` are notified.

The question this of course raises is wire traffic.

**Comment by Paranaix** [comment]
I believe that persisting the session for on_leave is a bad idea. A proper implementation would need to wait for every subscriber to return. That means ALL CALL, instead of pubsub.

**Comment by meejah** [comment]
If on_leave mirrors on_join, then there is *slightly* more info available in session.get() (namely: transport information). But, I don't think that should be a problem.

I think I'm repeating some discussion from onJoin etc here: but the spec. could put in an "extra=dict()" for wamp-proto and leave it up to the routers if they want to send more information along. A router implementation could then even make what extra information is sent configurable; e.g. transport information, session statistics (how long it lasted, bytes read/written, etc).

So, from a wamp-proto perspective the spec should put in things that are widely useful and that routers MUST include while leaving a hook for "more, but non-standard" information. The downside of this, of course, is that if you *depend* on this extra information you tie yourself to a particular router implementation ...

**Comment by oberstet** [comment]
> So, from a wamp-proto perspective the spec should put in things that are widely useful and that routers MUST include while leaving a hook for "more, but non-standard" information.

Agreed, that approach makes sense. It's a pragmatic approach, and sustainable.

IMO, the mandatory information should include: `sessionid`, `authid` and `authrole`.

And then a router MAY include an `transport` attribute, and the contents of that is router specific - or even router configuration specific.

**Comment by DZabavchik** [comment]
How about `wamp.session.on_leave_detailed` that will provide extra info, while existing `wamp.session.on_leave` can still be used when subscriber performs it's own session tracking?

**Comment by oberstet** [comment]
`wamp.session.on_leave` should have three positional arguments:

* `sessionid`
* `authid`
* `authrole`

Need to be fixed in the spec here: https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/advanced/ap_session_meta_api.md#wampsessionon_leave
