### ISSUE TITLE
Loadbalancing betwin 3 crossbar server

### ISSUE THREAD

**Issue by NassimAmroun** [wamp-proto/wamp-proto#248]
hello, 
Hello,
I want to do a system of load balancing between 3 servers crossbar , the three servers will connect to the main server, and when a client connect the main server provides it with the ip of server, and  realm.

I meet some problems :
I can't created several realm even in a router? how to do it.

Once the server log how to, up to dat the main server, with the number of connected client on the 3 servers.

I work with python

thx

**Comment by goeddea** [comment]
This is an issue tracker for the WAMP protocol spec, not a support forum for Crossbar.io, so you best address this to the mailing list - https://groups.google.com/forum/#!forum/crossbario.

Plus add more details there. As it is your question is somewhat cryptic.
