### ISSUE TITLE
WAMP libraries are slightly different-can WAMP spec help?

### ISSUE THREAD

**Issue by bradws** [wamp-proto/wamp-proto#251]
Hi!

My issue may not be directly related to the 'specification' as such, however I believe this to be a valid point and probably worth discussing.

I acknowledge that this is probably more to do with the implementation and specifics of WAMP libraries currently available.

In the spirit and goals of WAMP, and as an applications programmer, I noticed there is a slight (annoying) discrepancy of the WAMP libraries. For example, a person running an app using [AutobahnJS ](http://autobahn.ws/js/) cannot communicate _easily_ with another, say [Wampy](https://github.com/KSDaemon/wampy.js/) , or [WampSharp](https://github.com/Code-Sharp/WampSharp).

An example that immediately comes to mind is the standard RPC call. AutobahnJS returns it's results with a function thus:

```
// AutobahnJS
var add2 = function(args) {
      return args[0] + args[1];
};

session.register('com.myapp.add2', add2);
```

...however [Wampy](https://github.com/KSDaemon/wampy.js/) does it something like:

```
// Wampy
public add2( args ): any {
    return[ {},  args[0] + args[1] ];  //  result returned as array index [1]
}
session.register( "com.myapp.add2", add2 );
```

Writing apps handling these different scenarios is verbose. This requires re-writes, multiple code bases, etc.

Can/does WAMPY have anything to say for the ordering of parameters?

In my experience and use cases, passing around and returning data has always really been a single object (e.g. a 'Client' object) with the related data being contained in the sub field or sub objects.

Cheers,
bradws.

**Comment by oberstet** [comment]
The WAMP spec is about the *protocol*, not the *APIs* exposed by WAMP implementations. So this issue is - as you figure - misplaced here.

Also note that AutobahnJS does indeed fully interoperate with WampSharp. Do you have a specific problem rgd the interoperability of these 2 libraries? (ping @darkl)

Another note: AutobahnJS allows you to return a complex result with positional and keyword based values, see [here](https://github.com/crossbario/autobahn-js/blob/master/package/lib/session.js#L108). AutobahnJS exposes the full spectrum of complex args and kwargs for both call parameters and results.

If Wampy does not allow to do this, then this is a design issue in that specific library. See [here](https://github.com/KSDaemon/wampy.js/issues/22). The WAMP protocol spec can't do anything about that. (ping @KSDaemon )

**Comment by KSDaemon** [comment]
Hi all! Totally agree with @oberstet ! WAMP protocol is on one side, and of course, different implementations expose different API for the same WAMP features. And it is ok. Every developer create and architect api in a way that he is needed or is the best for him or his case. 

For bug in returning args array and dictionary at the same time — @bradws, you already created KSDaemon/wampy.js#22, and i agree — that should be fixed.

For publish case, you've shown: in js, you can not return 2 values from function at the same time, e.g. like in lua, but there can be cases, that are described in WAMP spec, when you need to return also some meta information, like { progress: true } . So single return value is not the case. In js it should be object or array. I decided to use array. And in different languages and implementations this can be done differently.

**Comment by bradws** [comment]
Duly noted and I cannot disagree. I'll need to add another API layer to each different WAMP library I use.
Cheers.

**Comment by darkl** [comment]
@bradws, this might get a bit better when we'll have Reflection for WAMP,
then code generators for different languages could be written, these will
ideally generate similar code regardless the target language.

Elad

**Comment by oberstet** [comment]
How do you add a layer that papers over the differences in  a C++ and a JavaScript library? Hint: you can't.

Why would you want to paper over the API differences in 2 WAMP libraries written in the same language? Hint: I don't see a point in doing so. Simply choose one and stick to that.

**Comment by konsultaner** [comment]
I totally have to admit to @oberstet. I implemented the wamp protocol as router and client. We had some discusions about some protocol specific definitions. This was more then enough to figure out. If the protocol tells you how to design your access to the protocol is too much and also impossible. Most languages have their flavors and styles. It is not the job of a protocol definition to decide how to implement it.

**Comment by Jopie64** [comment]
Why is this issue still open? It's already determined that it is not a spec issue. And even the referenced wampy bug KSDaemon/wampy.js#22 is fixed...

Also @darkl , what do you mean by Reflection for WAMP? You mean a common contract definition standard? When there is going to be one, it would be nice that one could build a contract based on WampSharp interface classes :)

**Comment by darkl** [comment]
I meant something like what I described in this [blog post](https://zelingher.wordpress.com/2016/06/19/introducing-typedautobahn/) under "Future" section.

Not sure when will this happen.
Elad

**Comment by oberstet** [comment]
As mentioned by @darkl , we do want to add standardized WAMP reflection meta API in the future (in the spec), but as discussed above, this is not about standardizing the _client language API_ (which needs to be free as designing a good client library API depends on the specific language).

Consequently, I'm closing this issue.
