### ISSUE TITLE
Publish & subscribe on same session

### ISSUE THREAD

**Issue by euprogramador** [wamp-proto/wamp-proto#259]
the available help on the link http://autobahn.ws/js/programming.html#subscribing-to-topics
quotes: "By default, the publisher will not receive an event it even Publishes When the publisher is itself subscribed to the topic subscribed to This behavior can be overridden.."

what I mean is that a code in the same session subscribe and publish an event will not be received and fails silently. it is not clear in WAMP documentation.

how to make the change this behavior by using the crossbar?

**Comment by meejah** [comment]
This is a bug-tracker, not a help forum. Did you try the mailing-list or IRC channel first?

For the record, you pass an option: http://autobahn.ws/js/reference.html#publisher-exclusion
