### ISSUE TITLE
14.4.2.1: Fix incorrect “it's”

### ISSUE THREAD

**Issue by FGasper** [wamp-proto/wamp-proto#272]
14.4.2.1 has the following phrase:

> To override the exclusion of a publisher from it's own publication …

There should not be an apostrophe here; i.e., it should be “from its own publication”.

**Comment by oberstet** [comment]
Thanks! Dunno why, but I am notorious at making this mistake;)

**Comment by FGasper** [comment]
Heh, you and umpteen other developers I know. :)

**Comment by KSDaemon** [comment]
Already fixed.
