### ISSUE TITLE
Details, Options, and HELLO (oh my!)

### ISSUE THREAD

**Issue by FGasper** [wamp-proto/wamp-proto#279]
The pattern where client-to-router messages have “Options” while router-to-client messages have “Details” is consistently applied except for HELLO. I’m assuming that this inconsistency is not intended? There are also ABORT and GOODBYE, which are ambidirectional: those use “Details”, but could they just as easily have been assigned “Options”?

What is the overall purpose of differentiating “Details” from “Options”? What would be lost were the spec just to name all of those fields “Metadata”?

**Comment by oberstet** [comment]
The general idea is:

* Options == knobs that influence the other peer
* Details == info that is provided to the other peer

"other peer": the peer the WAMP message is being sent to

---

Problem is when the "stuff" sent is actually partially "control" (which would suggest Options), and partially "informational" (which would suggest Details).

And as you note, the other source of ambiguity is when a message can travel both directions.

---

I don't consider this important, and I am very much against changing that. Many WAMP implementations have details/options naming in their code .. it would be a big effort to change all these, with practically no gain.

**Comment by oberstet** [comment]
@FGasper Well, what we could do however is explain the reasoning (and maybe also the "problems" as above). Do you think that is worth, or even more confusing?

**Comment by FGasper** [comment]
It might be nice to include a non-normative explanation of the logic behind the naming.

To me it still seems needless complication of the nomenclature to draw this distinction—particularly given the ambiguous cases. FWIW, my Perl implementation, Net::WAMP, will actually treat “Details”, “Options”, and “Metadata” interchangeably.

A naming change in implementations’ code wouldn’t be strictly necessary because it’s still speaking the same protocol, no matter which terms are used. Because the actual data structures don’t name the message parts, a given implementation could theoretically use whatever terms it wants and still be speaking WAMP indistinguishably from other implementations.

Anyway, this is kind of a minor point … but I thought better to raise it now than after an RFC. :)

**Comment by oberstet** [comment]
> To me it still seems needless complication of the nomenclature to draw this distinction—particularly given the ambiguous cases. 

Yes. I agree with that. It doesn't add value, and potentially is confusing, as it suggest semantics, which isn't strictly held up.

Question is whether a change "is worth the effort" and the resulting fallout ..

If we change it, `Metadata` would be one candidate. Another that comes to mind: `Extra`.

**Comment by FGasper** [comment]
Isn’t ```Extra``` already used in AUTHENTICATE?

**Comment by oberstet** [comment]
Right, in the WAMP spec there is a thing called `AUTHENTICATE.Extra` already (whereas in AutobahnPython that is named `auth_extra`).

Well, so maybe `Meta` or `Aux` (for auxiliary) ..

> I am mildly averse to "meta" .. because I can call anything "meta", and it feels somehow exaggerating given what it is .. matter of taste I guess.

**Comment by FGasper** [comment]
```Aux```/```Auxiliary``` seems reasonable to me, too.

**Comment by oberstet** [comment]
Alright. So I'm +1 on changing it to `Auxiliary`.

Needs consensus from other implementors (at least "some").

**Comment by FGasper** [comment]
Thank you!

**Comment by angiolep** [comment]
Thank you FGasper to have pointed this out! And thank you oberstet to have accepted his proposal.

At the time I implemented the WAMP basic profile in Scala language, I also noticed that the distinction between _details_ and _options_ didn't provide so much value. I also thought: _" this is pretty confusing and not so important"_ especially for those messages travelling in both directions!

I'd be also happy for that distinction to be removed from the specification in favour of much easier and consistent "_**auxiliary**_" dictionaries.

Messages could be defined as:

```
[HELLO, Realm|uri, Auxiliary|dict]
[WELCOME, Session|id, Auxiliary|dict]
[ABORT, Auxiliary|dict, Reason|uri]
...
[GOODBYE, Auxiliary|dict, Reason|uri]
...
```
and that will not impact on the existing implementations as field names (neither "detail" nor "option") are transmitted over the wire. Interoperability between existing implementations will be preserved. The benefit will be a better protocol specification to be submitted as RFC

**Comment by ecorm** [comment]
"Extra" and "Auxiliary" are synonyms. Whichever one is chosen, it's preferable to the confusing Details/Options duality as far as the specification is concerned.

@angiolep 
> and that will not impact on the existing implementations as field names (neither "detail" nor "options") are transmitted over the wire.

As oberstet has pointed out, it does impact existing **client** implementations in the sense that they already use use "details" or "options" in their APIs, code, and documentation. For example, `call( Rpc("foo").withOptions({"bar", 42}) )`. Hopefully, client library users will get the idea that details/options/auxiliary are interchangeable terms.

**Comment by FGasper** [comment]
@ecorm The clients will only be affected insofar as their terminology wouldn’t match the protocol specification. Since what goes over the wire won’t change, everything will just continue working.

**Comment by ecorm** [comment]
@FGasper Yup, just wanted to make sure everyone was aware that there would be an impact in terms of non-matching terminology.

**Comment by oberstet** [comment]
So there seems to be a lot of consensus that it should be fixed. Even when there is a chance it adds even more confusion.

> I am sorry, being guilty here: typical "too much thoughts that seemed to make sense ... but actually don't";)

**Comment by oberstet** [comment]
So how we are gonna do a "final call" on this?

My vote: `Aux` (as replacement for both `Options` and `Extra`).

**Comment by goeddea** [comment]
+1 on "aux". easy to grasp, easy to write

**Comment by KSDaemon** [comment]
+1 on “aux”

**Comment by gammazero** [comment]
To me `aux` does not seem any more informative that `options`.  How about something that is a bit more familiar for users of various languages.  Since `options` == knobs/control this means it provides additional parameters, how about `params` or `args` or `kwargs`?

**Comment by konsultaner** [comment]
+1 on params
-1 args or kwargs

**Comment by Jopie64** [comment]
Not args or params because this metadata can also be part of e.g. RPC's which in themselves already have args or params. So that would be confusing.
So since it's meta data, why not simply 'meta'? 😄
I'd be +1 on aux too though...

**Comment by oberstet** [comment]
> To me aux does not seem any more informative that options.

It isn't more informative, but that's not the goal: the goal here is to remove the artifical and confusing distinction between `options` and `details`.

> how about params or args or kwargs ..

No, really, this is confusing wrt to application payload. `aux` is for knobs that are set from user code, but it is not for transporting actual user data. This is what `args`/`kwargs` is for. Eg a router may opt to only allow spec'ed knobs, and disallow (or ignore) any custom knobs. A router may also limit the types or size of the `aux` message parts (separately from any limits on types/size it may impose on app payload - `args`/`kwargs`).

> So since it's meta data, why not simply 'meta'?

nothing "wrong" or "right" here;) but https://github.com/wamp-proto/wamp-proto/issues/279#issuecomment-292190066

---

From above thread, I would say: most have voted for (or are at least fine with) replacing `details` and `options` with `aux`. Let's go for that and move on - it's not _that_ important;)

**Comment by gammazero** [comment]
Thanks @Jopie64 and @oberstet for clarifying the point I was missing.  So, after rethinking this...
Currently:
- options = control: things that influence how the message is processed
- details = data: items providing informational information(data)

I think retaining this distinction is important, and if we look at the spec with that definition in mind, the confusion about options vs details disappears.

As @FGasper says, "There are also ABORT and GOODBYE, which are ambidirectional: those use “Details”, but could they just as easily have been assigned “Options”?"

I disagree, and the use of Details in ABORT and GOODBYE is to supply information, not to control message processing.  So, Details is correct. 

Very sorry if I am beating a dead horse here, or wasting time on a trivial issue, but after reviewing the existing spec, the comments above, and considering possible ramifications, I agree with the comment here: https://github.com/wamp-proto/wamp-proto/issues/279#issuecomment-292073184 and suggest that this matter be closed as is.

**Comment by oberstet** [comment]
Ok, works for me too. This is a waste of time ..
