### ISSUE TITLE
More information for wamp.subscription.on_delete

### ISSUE THREAD

**Issue by i2xS** [wamp-proto/wamp-proto#287]
same problem as here https://github.com/wamp-proto/wamp-proto/issues/238
Currently `wamp.subscription.on_delete` only receives `subscription_id` as argument and there is no chance to get uri of this subscription because calling `wamp.subscription.get` in `on_delete` handler with this id raises `wamp.error.no_such_subscription`

**Comment by oberstet** [comment]
No, this isn't the same. A subscription isn't identified by a URI.
