### ISSUE TITLE
Extend black/white listing to arbitrary session attributes

### ISSUE THREAD

**Issue by gammazero** [wamp-proto/wamp-proto#291]
WAMP allows Subscriber Black- and Whitelisting on sessionid, authid and authrole.  However, subscribers may have a number of attributes that group them in various ways.  A subscriber may be a member of any number of groups, and publishers want to publish messages to various combinations of those groups.  There are two ways to accomplish this without having to have a separate topic for every combination of groups:

1. Publisher must determine the group membership of each subscriber, then b/w list by subscriber sessionid to send message to correct recipients.  This may be difficult for publishers and is fragile w.r.t. message history (cannot save history filtered by session id). 
2. Have router do b/w listing on arbitrary session attributes.

I propose option 2 as it is a natural extension of the existing b/w listing functionality.  It assumes that clients use the HELLO message details to put arbitrary attributes in their session.

For example, if a publisher wants to publish an event to all Sales Managers in California and Hawaii working on project X, Y, and Z, then whitelist: `eligible_authrole: ["manager"]`, `eligible_unit: ["sales"]`, `eligible_location: ["CA", "HI"]`, `eligible_project: ["X", "Y", "Z"]`.

Blacklisting would work similarly to exclude specified groups.

The Black- and Whitelisting would be extended by recognizing the publish options `exclude_xxx` and `eligible_xxx`, accompanied with a list of string values to match against, where `xxx` is he name of any attribute in the session details.

As an example, to allow sessions with org_id=ycorp or org_id=zcorp, a PUBLISH message specifies the following option:
```
eligible_org_id: ["ycorp", "zcorp"]
```

Two rules would be added to this [section](http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#rfc.section.14.4.1.3) that states, "An (authorized) Subscriber to topic T will receive an event published to T if and only if all of the following statements hold true":

- if there is an `eligible_xxx` attribute present, the Subscriber's `xxx` value is in this list
- if there is an `exclude_xxx` attribute present, the Subscriber's `xxx` value is NOT in this list

**Comment by oberstet** [comment]
> However, subscribers may have a number of attributes that group them in various ways. 

Yes, and I don't see how WAMP routers could be optimized for an open-end of ways to define and combine those attributes. I am against that. You can add custom attributes to events, and then enforce in app code whatever your requirements are, but IMO we should keep filtering simple. In a way, this is a misfeature altogether anyways in many ways (but agreed, not all): binding app code to authid/authrole or session IDs is bad. most of the time, stuff should be reflected in URI space then, and matches using pattern based registrations or subscriptions.

**Comment by gammazero** [comment]
The use case addresses situations where a publisher needs to make sure an event is not received by unintended recipients.  This would not be open-ended, and would have a specific ways to combine attributes:  Router would look to see if a black or white list was defined for each attribute in session, if so, then see if the session attribute's value matched any of the values in the black or white list, and act accordingly.

If this seems like building on a feature that is already bordering on a mis-feature, or is encouraging misuse of WAMP then lets close this issue.

**Comment by oberstet** [comment]
>  would have a specific way to combine attributes

Sure. But where does it stop? Next on the table is then arbitrary boolean expressions over presence or non-presence of some attribute;) What I mean is: it is potentially open-ended. What you asked for is one specific way of a filtering logic, and ultimately, one could ask for a universal capability that allows me to express any filtering logic I wish for. So this road is not sustainable, and keeping it simple seems attractive;)

**Comment by oberstet** [comment]
Here is different way that might result in similar behavior you might be after: in fact, there is unfinshed code (hooks) in crossbar for payload validation. Those are meant for use with payload schema definitions, eg JSON schema for verifying the payload. So there is a router-side, static (in as, "loaded") representation of the filtering "ok vs not-ok". However, this is a router implementation feature, and it is also not about narrowing down a specific receipient list further like with bw listing ..

**Comment by oberstet** [comment]
following up, I think as a router implementation hook, this can actually work and fit in. a hook is user code in a general programming language (eg python), means no wheel to reinvent;)

@gammazero here https://github.com/crossbario/crossbar/issues/1248

so I am closing this one ..
