### ISSUE TITLE
Add WAMP message stream to RawSocket messages

### ISSUE THREAD

**Issue by konsultaner** [wamp-proto/wamp-proto#292]
I have a use case where I need to send larger filesizes then 16MB over [RawSockets](https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/advanced/ap_transport_rawsocket.md). To have a message size of 16M makes sense, because the read and write network buffer should not be larger for a lot of clients anyway. I would like to see one more message type

´´´
0 = WAMP message (or continuation frame)
1 = Ping
2 = Pong
3 = WAMP message stream (containig the amount of wamp messages that make one message in the next 3 byte)
´´´

as long as multiplexing is not implemented, it is very easy to use the new frame types to support even larger file transfer without having to use propressive calls or other logical payload splitting.

**Comment by oberstet** [comment]
yeah, very easy, but wrong, because it is a hack. streams at the transport level without anything like fragmentation and either multiplexing and/or priorization introduces head of line blocking. anyway, better put the effort into progressive calls, rather hacks.

**Comment by oberstet** [comment]
in fact, here is the thing: once we have progressive calls and progressive results, that is actually like streams multiplexed at the per call level.

**Comment by konsultaner** [comment]
> yeah, very easy, but wrong, because it is a hack. streams at the transport level without anything like fragmentation and either multiplexing and/or priorization introduces head of line blocking. anyway, better put the effort into progressive calls, rather hacks.

@oberstet Thats right, its a hack talking about streams. I do get what you mean. The idea came up thinking about WebSockets continuation frames. I thought it would be handy if RawSockets had something similar. My router can now send very large messages using WebSockets but only 16MB/Message on RawSockets. I was happy to increase performance not using WebSockets for Java-To-Java-Communication.

**Comment by konsultaner** [comment]
I should have rather called the 3

```
3 = WAMP chunked message
```

or something similar

**Comment by oberstet** [comment]
@konsultaner I get what you are after, but what I am trying to say: RawSocket was _designed_ to be simple - simpler (in my experience) to implement than WebSocket. If you want the features of WebSocket (eg fragmentation, or per-message-deflate compression), use WebSocket.

Also, in my view, fragmentation without a path to expose backpressure into app code is pointless .. and the right path to do that latter is via progressive call/result hooks: eg making the progressive call handle returned to app code a Twisted producer for the progressive calls, so it can be throttled from the guts within a WAMP client library.

**Comment by konsultaner** [comment]
> RawSocket was designed to be simple
@oberstet if this is a main design goal, then I totally agree! 
I found a way to solve my problem by upgrading (second handshake) to a 64bit header :) So it's fully compatible to the wamp definition and lets me implement my special usecase
