### ISSUE TITLE
Transport Resumption

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#293]
# Intro

Thinking about the open PR and issue rgd **session resumption**, in particular, trying to explore the use cases, I came up with an alternative approach to what I think is one important use case:

* making short connection losses, and re-establishment of complete new transports to uplink WAMP router from a WAMP client _transparent at the app level_.

I'll describe below. So we could kick session resumption for this one, kick this new one, or kick both. But I think in any case, below could help the discussion - what I am trying to say: I don't want to needlessly open new cans with worms;) Btw, happy that we make progress on just sharpening the spec rgd whats there already=)

# Transport Resumption

## Feature

Transport resumption allows a WAMP client to recover from a connection loss to the uplink WAMP router, where the connection loss only lasts for 100s ms up to 10s seconds at maximum.

## Use case

One use case for transport resumption could be handover when roaming Wifi networks. Handover times between adjacent Wifi networks typically are in the range of 250-1000 ms. Using transport resumption, Wifi handover happens without the application layer noticing anything (not "transport lost" errors), but only slight delays in WAMP response time.

## Implementation sketch

Instead of writing the serialized WAMP raw message (a bytes string) to a transport, the byte string is pushed to an outgoing queue.

Similarily, incoming WAMP raw messages (byte strings) are first pushed to an incoming queue.

All raw messages are assumed to have sequence numbers, and incoming messages acknowledge the (ordered) reception of messages that have been sent from the outgoing queue of the former client.

When the underlying transport is lost, the queues will hold and buffer more messages (outgoing) up to some limit, and when a new transport was established in due time, and providing the last processed incoming message sequence number, the queues are emptied, or messages resent with sequence numbers higher than announced by the (re)connecting client.

Hence, when the client looses the uplink router connection during a Wifi handover, the application only sees a slight delay in responses to WAMP requests (eg CALL a remote procedure, or PUBLISH with acknowledge etc), but no errors.

When the client does not come back in due time (eg the queue has reached its limit), the other peer will then get errors and the queue marked dirty. When the client then connects and tries to resume the transport, and error is returned: "cannot resume transport, as transport is already final-failed".

**Comment by oberstet** [comment]
see https://github.com/wamp-proto/wamp-proto/pull/264

**Comment by KSDaemon** [comment]
Hi all, guys!
Actually, there is a usefull thoughts in Tobias words. I can say, that wamy.js (JS WAMP client library) and Loowy (Lua WAMP client library), both use the same approach:
If client sessions is determined disconnected (due to transport problems), they try to reconnect, and on success clients resubscribe and reregister to topics and procedures. Also both clients maintain queue of WAMP messages, issued during connection loss, so if connection is reestablished, all outgoing messages, such as RPC Call, Publish, Subscribe, etc, are sent to WAMP Router.

**Comment by oberstet** [comment]
@KSDaemon cool! actually, you have 2 features there:

* "if connection is reestablished, all outgoing messages .."
* "on success clients resubscribe and reregister to topics and procedures"

---

what I describe above works slightly different: both sides (client and router) keep queues, and the session state on router side is maintained while a transport is reestablished. so there is no need to resubscribe/reregister.

also, there are more subtle details like this: a client sends a CALL, and the transport is lost. since the client hasn't received a response yet (a RESULT), it doesnt know if the router has even received the initial CALL when the client is reconnecting. so it send the CALL again. but then, how does the router know this isn't a valid 2nd call, but only the client recovering from the loss of transport? I think we need the sequence number thing at the raw WAMP message level ..

**Comment by Jopie64** [comment]
Shouldn't session resumption be a thing of the underlying protocol? Eg websocket?
Or an extra layer between protocols e.g. between websocket and wamp?

**Comment by KSDaemon** [comment]
@Jopie64 Well, actually that would be cool. But, i don't see that is possible in common. That is cool, if you control the underlying communication layer. But, for example, in browser enviroment, you have no options, just use high level websocket api, available to you. And in this case you, as WAMP implementer, need to design your own high level architectural logic to handle communication problems.

**Comment by oberstet** [comment]
> Shouldn't session resumption be a thing of the underlying protocol? Eg websocket?

No, this is mixing layers: a _session_ is a WAMP thing, and a transport won't be aware (nor should it) of the details of a WAMP session ...

Note that this new issue here is about _transport_ resumption - which obviously is below the WAMP session level.

In essence, WAMP requires a transport to have these characteristics:

* message-based
* reliable
* ordered
* bidirectional (full-duplex)

http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#rfc.section.5.3

For resumable transports, this isn't enough: we need a message sequence ID. Currently, this is only avail at the WAMP message level ... mmh .. need to untangle that ..

**Comment by oberstet** [comment]
closing .. see the discussion here https://github.com/wamp-proto/wamp-proto/pull/264

**Comment by ecorm** [comment]
Is this now part of the spec, or what?

**Comment by oberstet** [comment]
>  It seems this is still in the sketch phase.

yes, that's true. it is one of the gray areas .. also, no prototype or experimental implementations I am aware of  ...
