### ISSUE TITLE
Testament API scope keyword `detatched` is misspelled

### ISSUE THREAD

**Issue by gammazero** [wamp-proto/wamp-proto#316]
The WAMP specification specifies one of the Testament scope keywords as `detatched`.  This should be spelled `detached`.

It appears that Crossbar uses the spelling `detatched`.  The [nexus](https://github.com/gammazero/nexus) router uses the spelling `detached`.  I do not know if any other WAMP routers implement the testament API.

**Comment by oberstet** [comment]
@gammazero rgd crossbar: yeah, typo .. https://github.com/crossbario/crossbar/issues/1362
