### ISSUE TITLE
Need error response to stop progressive yield

### ISSUE THREAD

**Issue by gammazero** [wamp-proto/wamp-proto#319]
If a callee is responding with progressive yields, and the caller receiving the results closes, then the callee has no way to know to stop sending progressive yields.

Consider the case where the callee is using progressive results to stream some content a caller, and it may be a very long time before the callee stops sending.

The testament API could be used to notify callees about the disappearance of a client, but callees would need to know before hand to set this up, so it is really a work-around.

**Comment by Jopie64** [comment]
The advanced profile supports [call cancelling](https://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#cancel). I'd suggest to use [INTERRUPT](https://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#rfc.section.14.1.1.4) to let the callee know the caller session has closed.

And although it is not stated explicitly in the RFC, if I remember correctly the Crossbar.io router already behaves like this.
Maybe it would be a good thing to make this behavior mandatory in the RFC.

**Comment by gammazero** [comment]
The only issue I have with that approach is that handling the situation is dependent on a separate feature, call canceling, and cannot be handled completely within the functionality of the progressive results feature.

I would hope that any router that supports progressive results also supports call canceling, and same for any client.

**Comment by oberstet** [comment]
@gammazero yeah, this is "unspecified behavior". and agreed, in this case, we could and should probably just specify what should happen, because the desirable behavior seems obvious (you describe it already). Having the router sending a proactive INTERRUPT seems to address the situation, agree with @Jopie64

> The feature is orthogonal to call canceling, since the INTERRUPT is sent proactively - so we might think about adding this to the feature "progressive call result" instead .. or we might require a router to signal support by sending both feature "progressive call result" and "call canceling" - which then implies that there cannot be a router that support call canceling (active) and progressive call result, but not interrupting an ongoing progressive call result stream.

**Comment by gammazero** [comment]
Dealer sending INTERRUPT makes sense.  It really is a form of call canceling, and I think it makes sense for a router to signal support for both feature "progressive call result" and "call canceling", since the ability to cancel progressive results is important for both routers and for callees.

How does this sound so far:

----
Upon receiving an `YIELD` message from a _Callee_ with `YIELD.Options.progress == true` (for a call that is still ongoing), the _Dealer_ will immediately send a `RESULT` message to the original Caller with
```
    RESULT.Details.progress|bool := true
```
If the original _Caller_ is no longer available (has left the realm), then the _Dealer_ will send an `INTERRUPT` to the _Callee_.  The `INTERRUPT` will have `Options.mode` set to `"killnowait"` to indicate to the client that no response should be sent to the `INTERRUPT`. 
```
[INTERRUPT, INVOCATION.Request|id, Options|dict]
```
Options:
```
INTERRUPT.Options.mode|string == "killnowait"
```

**Feature Announcement**

Support for this advanced feature MUST be announced by _Callers_ (role := "caller"), _Callees_ (role := "callee") and _Dealers_ (role := "dealer") via
```
    HELLO.Details.roles.<role>.features.
         progressive_call_results|bool := true
```
Additionally, _Callees_ and _Dealers_ MUST support Call Canceling, which is required for canceling progressive results if the original _Caller_ leaves the realm.

---- 
If this is good, I can add to spec as well as update the sequence diagrams.

**Comment by gammazero** [comment]
The above proposal closes an important safety gap.  In cases where progressive results are used to stream data to callers, and network connectivity is unreliable, callers my often get disconnected in the middle of receiving progressive results.  Recurring connect, call, disconnect cycles can quickly build up callees streaming results to dead callers.  This can overload the router and certainly does nothing good for already poor network connectivity.

I have a working implementation of the above in the [nexus](https://github.com/gammazero/nexus#wamp-v2-router-library-client-library-and-router-service) router, and think in testing it has shown to be valuable in the situation described above.  
 
A possible criticism with the proposal is, if a _Callee_ supports Progressive Call Results but not Call Cancelling, progressive results will simply not work and there will not be a direct indication to the client as to why.  I think this is acceptable, since those clients should be very rare, and this strikes a good balance between not breaking existing implementations while providing safe, well defined behavior.  Thoughts?

**Comment by oberstet** [comment]
@gammazero IMO the text you propose is already perfect, ready for the spec. One more gap closing .. cool!

> I am also +1 on adding the first paragraph of your last comment as a use-case and motivation of the feature and specific behavior defined. This can be a very useful "2nd factor" of information for implementors - when I understand the motivation of the spec, I can fill in my understanding of the formal spec text parts from this context.
