### ISSUE TITLE
Contributing guidelines 'most current draft document' link is broken

### ISSUE THREAD

**Issue by LaurenceGA** [wamp-proto/wamp-proto#327]
This isn't editorial or design...
But the link for 'most current draft document' currently goes to "https://tools.ietf.org/html/draft-oberstet-hybi-crossbar-wamp".
I get a 404 here.
I tried doing a search on tools.ietf.org and only found [this expired draft](https://tools.ietf.org/id/draft-oberstet-hybi-tavendo-wamp-02.html).

Also applied to 'draft version' link above that one.

On a related note, the README for this repo has a broken gitter link ("https://gitter.im/crossbar/WAMP").

**Comment by oberstet** [comment]
yeah, as we evolved the build tooling .. that broke at one point=( thanks for reporting.

the links here and the published spec are now fixed (and also now build and automatically), pls see:

* https://github.com/wamp-proto/wamp-proto#the-web-application-messaging-protocol
* https://wamp-proto.org/spec.html
