### ISSUE TITLE
What happens to outstanding INVOCATIONs when you UNREGISTER?

### ISSUE THREAD

**Issue by GregRos** [wamp-proto/wamp-proto#329]
I'm writing my own WAMP client for JS over at https://github.com/GregRos/wampus, and I'm a bit unclear on what happens to existing INVOCATIONs when you UNREGISTER, as well as invocations sent during the process.

So let's say events go like this:

1. User registers procedure `example`
2. User receives INVOCATION `example.1` 
6. User receives INVOCATION `example.2`
3. User sends `UNREGISTER(example)`
5. User sends `YIELD(example.1)`
4. User receives INVOCATION `example.3`
5. User receives `UNREGISTERED(example)`
6. User receives INVOCATION `example.4`

The questions are:

1. What will the router do with the result for `example.1`?
2. What should the client do with `example.2` and `example.3`?
3. Will a router ever send `example.4`?

**Comment by GregRos** [comment]
Oops, I see this issue already exists. Sorry.

**Comment by ecorm** [comment]
For reference, this is the duplicate issue: #283
