### ISSUE TITLE
When sending an Invocation ERROR response, what's the difference between Details and ArgumentsKw?

### ISSUE THREAD

**Issue by GregRos** [wamp-proto/wamp-proto#333]
ArgumentsKw lets me send a bunch of named arguments to the caller. But then there is Details, which seems to allow me to do the same thing. When should I use one or the other? Why do I have these two options?

In other ERROR messages, it's the only field that contains data on the error. 
In non-ERROR messages, it's supposed to contain only protocol options and not custom data.

Even the example seems to ignore it:
```
[8, 68, 6131533, {}, "com.myapp.error.object_write_protected", ["Object is write protected."], {"severity": 3}]
```

(To be honest, I don't really like being able to send arguments via both Arguments and ArgumentsKw, and rather there were only one way, but now there's this third thing to consider).

**Comment by KSDaemon** [comment]
Hi @GregRos! Well, from some point you're right! 
But, i think you should treat this options differently: Arguments array and Arguments dictionary, as it is named — are arguments to some RPC or Topic aka payload, but `options` — contains additional supplementary information regarding call or publishing. It contains some protocol defined options like `disclose_me` or `eligible_authid ` and also can contain other user defined attributes. It is mostly used to provide information about how payload should be processed and not to mess it all up. 
Moreover, arguments — are basic things and any client must support them, rather then different options, that are related to advanced profile.

**Comment by gammazero** [comment]
In short, arguments are information communicated to other client(s) as part of the message.  Options are for the router, to tell it how to handle the message.

**Comment by GregRos** [comment]
No, this is not what the specification says. I am not talking about `options`, which is used for different messages to specify options for the router. I am not talking about `ERROR.Details` in an ERROR message, which is used to send custom information.

The specification states that the `ERROR.Details` field:

> Details is a dictionary with additional error details

Some ERROR messages, such as the one sent after SUBSCRIBE, do not have any other field to indicate this information. From the spec:

>  `[ERROR, SUBSCRIBE, SUBSCRIBE.Request|id, Details|dict, Error|uri]`

The specification has zero examples of what this field might contain. The closest I can find is `ABORT.Details`, which does have an example showing it's used for custom information:

> ABORT.Details MUST be a dictionary that allows to provide additional, optional closing information (see below)
>  `[3, {"message": "The realm does not exist."}, "wamp.error.no_such_realm"]`

**Comment by KSDaemon** [comment]
Well, just a few examples from my own:
* PRC can not connect to db. In this case i extend Details with db adapter error info
* No write permissions to directory on RPC side. Also, to understand what was wrong — you can extend Details dict with this info

**Comment by KSDaemon** [comment]
@GregRos Of course you can do so :) Specification doesn't disallow that. You asked us what are this things for — we answered our thoughts on this. You can do as you want, just be consistent within your system.
