### ISSUE TITLE
Complete embedded demo

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#335]
Here https://wamp-proto.org/intro.html#what-can-i-do-with-this from here https://github.com/wamp-proto/wamp-proto/blob/master/docs/intro.rst#what-can-i-do-with-this

Just needs ABJS and hooking up the JS .. and some CSS tweaking. The basic structure is already integrated.

**Comment by goeddea** [comment]
tested with the local build of the docs

**Comment by oberstet** [comment]
doesn't work in prod: Laden fehlgeschlagen für das <script> mit der Quelle "https://s3.eu-central-1.amazonaws.com/_static/js/autobahn.min.js". intro.html:280:1
Laden fehlgeschlagen für das <script> mit der Quelle "https://s3.eu-central-1.amazonaws.com/_static/js/cursorbox.js".

https://s3.eu-central-1.amazonaws.com/wamp-proto.org/intro.html

**Comment by oberstet** [comment]
@goeddea it still does not work
![bildschirmfoto von 2019-01-12 07-59-48](https://user-images.githubusercontent.com/233340/51070377-7fd69c80-1640-11e9-9b84-52836742a08b.png)

**Comment by goeddea** [comment]
works now

closing
