### ISSUE TITLE
Only the first page of the website is working

### ISSUE THREAD

**Issue by akarelas** [wamp-proto/wamp-proto#337]
This page works: https://wamp-proto.org/

But if I click on these links from the navbar, they don't work: https://wamp-proto.org/why/index.html https://wamp-proto.org/compared/index.html etc

They return this:

```xml
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>why/index.html</Key><RequestId>F5C37AB32FD88DC4</RequestId><HostId>rGipILyf3u565/dzSCMV4nDShurK839jq6P+5uh3qnX7tpDIbnzLlwBQzcztnSou2Dlo39mkQ5g=</HostId></Error>
```

**Comment by Jopie64** [comment]
Not sure whether it's WIP, but currently on this page, the HTML tags are visible in the browser:
https://s3.eu-central-1.amazonaws.com/wamp-proto.org/routing.html

Still the layout has become nice! Good work!

**Comment by akarelas** [comment]
The problem is that the old website was cached on my browser, and that's what I saw.

Therefore you should set the cache headers correctly to avoid this problem from now on.

**Comment by oberstet** [comment]
the web site is hosted via a CDN, which takes some time to distributed and cache ..
