### ISSUE TITLE
Describe allee black- and whitelisting

### ISSUE THREAD

**Issue by GregRos** [wamp-proto/wamp-proto#342]
In [11.2 Advanced Profile](https://wamp-proto.org/_static/wamp_latest.html#advanced-profile), Predefined URIs, it says:

> A Dealer could not perform a call, since a procedure with the given URI is registered, but Callee Black- and Whitelisting and/or Caller Exclusion lead to the exclusion of (any) Callee providing the procedure.
> ```
> wamp.error.no_eligible_callee
> ```

These features don't exist. I'm not sure what the intent here is, but the paragraph seems to suggest they do.

**Comment by oberstet** [comment]
https://wamp-proto.org/_static/wamp_latest.html#subscriber-black-and-whitelisting

**Comment by GregRos** [comment]
@oberstet 
Can you *please* read the issue before closing it?

You just linked to **subscriber black and whitelisting**. The paragraph I linked to talks about **callee black and whitelisting**, which does not exist. It talks about an error that arises when a procedure call fails because this non-existent feature was used. 

This has nothing to do with PubSub at all.

**Comment by oberstet** [comment]
Sorry, yes sure, I misread your comment. This is confusing indeed: we describe an error for a situation that isn't described itself: with shared registrations, a caller might want to limit the callers considered by the router for forwarding the call to.

**Comment by GregRos** [comment]
It sounds like a good feature. But this feature isn't in the specification yet, and who knows when it might be added. 

Wouldn't it make more sense to just remove the confusing paragraph, and just add it back in later when the feature is in the specification?

**Comment by oberstet** [comment]
fixed via https://github.com/wamp-proto/wamp-proto/pull/379
