### ISSUE TITLE
[Question] Is there any way to have a JSON payload on each package for serverless WebSocket

### ISSUE THREAD

**Issue by mariotoffia** [wamp-proto/wamp-proto#350]
Hi,

I'm trying to map WAMP using [AWS WebSocket](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway) support on the API Gateway. But it relies on routing each incoming request and I don't see any standardized way of providing such info on each package.

Have I missed something?

Cheers,
 Mario

**Comment by oberstet** [comment]
I haven't looked deeply, but AWS WebSocket API Gateway seems to be poor mans, ad-hoc redesign of the RPC part of WAMP (well, only the very basic stuff, and not even the Callee side, only JSON, etc etc):

> To route messages based on the message content, the WebSocket API expects JSON-formatted messages with a property serving as a routing key.

So no, we don't and won't support this broken design;) Just use WAMP.
