### ISSUE TITLE
remove goeddea as author

### ISSUE THREAD

**Issue by goeddea** [wamp-proto/wamp-proto#351]
I haven't worked on the spec in a long time, and the only reason to add me as an author was to allow me to publish the spec to the IETF.

There are others who have contributed much more to the development of WAMP or have worked more on the spec by now. 

Please remove "Alexander Gödde" from the authors list.

**Comment by KSDaemon** [comment]
@oberstet What do you think? In w3c spec authors: you and Alexander are specified directly, no automatic generation, i can fix it. 
But i think, that @goeddea should be kept in spec contributors.

**Comment by oberstet** [comment]
@KSDaemon yep, agreed, perfect!

**Comment by KSDaemon** [comment]
Great! I'll make it.
