### ISSUE TITLE
callee wamp.error.unavailable + transparent call rerouting

### ISSUE THREAD

**Issue by binaek89** [wamp-proto/wamp-proto#352]
This is to enable the ability of a RPC service provider to `REJECT` an `INVOCATION` request coming in.

This message is transmitted solely from the `CALLEE` to the `DEALER`.

When the `DEALER` receives this message from the `CALLEE`, it will select another `CALLEE` to process the original `CALL` request which corresponds to the original `INVOCATION` request. 

The original routing rules still apply. If the `DEALER` runs out of `CALLEE`s or is unable to select a new `CALLEE` (when `first` or `last` is the routing logic selected), it returns an `ERROR` message to the `CALLER`.

### Use Case
A use-case is when a `CALLEE` is too heavily loaded to be able to process a request or when the application instance running the `CALLEE` service is aware that it will be shutdown as a part of a scale-in exercise by the orchestrator - wherein, the instance is expected to finish execution of running executions, but should not take up new jobs. 

This will enable the `DEALER` to handle such a case without the `CALLER` ever having to know about it.

### Suggested change in specification

This will require a new `Message Code`.

An extension to the protocol could take the form:

#### Invocation REJECT

If the Callee purposefully wants to reject execution of the invocation, the Callee sends a `REJECT` message to the Dealer:
```
[REJECT, INVOCATION, INVOCATION.Request|id, Details|dict]
```

where

* `INVOCATION.Request` is the ID from the original `INVOCATION` request previously sent by the Dealer to the Callee.
* `Details` is a dictionary with additional details.

*Example*
Assuming `Message code` to be `71`
```
[71, 68, 6131533, {}]
```

**Comment by mbonneau** [comment]
Having `REJECT` would also allow callees to fend off new requests if it is shutting down. This would be transparent to the caller.

May help with the use case I describe here:  https://github.com/wamp-proto/wamp-proto/issues/283

This would allow the callee session to finish up all `INVOCATION`s and then `UNREGISTER`. Although in that case it is still possible that the `UNREGISTER` is sent with `INVOCATION`s in transit.

**Comment by binaek89** [comment]
> Having `REJECT` would also allow callees to fend off new requests if it is shutting down. This would be transparent to the caller.
>
That is the use case I was suggesting.
> 
> May help with the use case I describe here: #283
> 
> This would allow the callee session to finish up all `INVOCATION`s and then `UNREGISTER`. Although in that case it is still possible that the `UNREGISTER` is sent with `INVOCATION`s in transit.

Even if there is an in-flight `INVOCATION`, the `CALLEE` is aware that it WILL be shutdown and therefore will probably respond with a `REJECT` nonetheless. If the WS Session is open, the `DEALER` will receive it and can act accordingly.

**Comment by LaurenceGA** [comment]
I'm not so sure the use case justifies a new message code. Callee availability should be handled by whether it is registered or unregistered as a callee.

If load is heavy then you may need a better dealer load balancing algorithm.
If it is shutting down, it should unregister itself and finish whatever pending invocations it has (I still think that's the best solution to #283).

Why is this insufficient?

**Comment by Jopie64** [comment]
FWIW I agree with @LaurenceGA. When agreed upon proposed behavior of #283, the use case for `REJECT` can also be achieved by (temporarily) unregistering the procedure.

**Comment by oberstet** [comment]
Rereading above .. I think the use case

> This will enable the DEALER to handle such a case without the CALLER ever having to know about it.

could also be handled without introducing a new WAMP message type, but an official error URI returned in ERROR message by the callee: `wamp.error.shutting_down`.

upon respective configuration, and when executing invocation of a shared registration, a router might then transparently retry on a different callee.

**Comment by binaek89** [comment]
@oberstet having a transparent error message definitely works.

Drawing from HTTP 503 analogy, I believe a message like `wamp.error.unavailable` will probably give more playroom since that will also take care of the case where the `CALLEE` is too busy to handle the request and intends for the router to forward the request to another `provider`.

**Comment by oberstet** [comment]
Ok, so it seems like we have "rough consensus" .. I changed the title to (hopefully) better reflect the proposal and removed the "needs discussion" label (we have upvotes from at least 3 implementors).

Next step would be: a PR with concrete spec (AP profile) text proposal ..

**Comment by oberstet** [comment]
fixed via https://github.com/wamp-proto/wamp-proto/pull/365 - thanks @binaek89 =)
