### ISSUE TITLE
Confused about "Calls matching multiple registrations" examples

### ISSUE THREAD

**Issue by JohnDoee** [wamp-proto/wamp-proto#353]
[The examples in the RFC](https://wamp-proto.org/_static/gen/wamp_latest_ietf.html#calls-matching-multiple-registrations) are either wrong or confusing, it says

    Call request RPC URI: 'a1.b2.c3.d4.e5' → 
        no exact match, no prefix match, 2 wildcard matches (4,5), 
        select longest one. Use RPC 5

... but the registered URIs contain two prefixes that'd match, 2. and 3.

**Comment by gammazero** [comment]
PR submitted to fix example.  Thank you.

**Comment by oberstet** [comment]
this was fixed via PR #354
