### ISSUE TITLE
Request: more detailed SCRAM test vector

### ISSUE THREAD

**Issue by konsultaner** [wamp-proto/wamp-proto#366]
I started an [open source wamp client for the dart language](https://github.com/konsultaner/connectanum-dart). I also started to implement scram authentication with pbkdf2. I used the test-vector of [RFC7677](https://tools.ietf.org/html/rfc7677), but I made a mistake somewhere. Its hard to find the issue without having a more detailed test vector.

@ecorm This is my test vector, but `saltedPassword`, `clientKey`, `storedKey` or/and `clientSignature` is wrong. Is it possible for you to use the [RFC7677](https://tools.ietf.org/html/rfc7677) vector (or any other you have somewhere) and send your values of `saltedPassword`, `clientKey`, `storedKey` and `clientSignature` to help me and other implementers to fix issues? My implementation is [found here](https://github.com/konsultaner/connectanum-dart/blob/master/lib/src/authentication/scram_authentication.dart#L76).

**[UPDATE]** I finally got it working. These values are correct now:

```dart
var user = "user";
var password = "pencil"
var clientNone = "rOprNGfwEbeRWgbNEkqO";
var salt = "W22ZaJ0SNY7soEsUEjb6gQ==";
var iterations = 4096;
var kdf = "pbkdf2"
var channelBinding = null;
var serverNonce = "rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF$k0";
var authMessage = "n=user,r=rOprNGfwEbeRWgbNEkqO,r=rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF$k0,s=W22ZaJ0SNY7soEsUEjb6gQ==,i=4096,c=biws,r=rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF$k0"
var saltedPassword = [196, 164, 149, 16, 50, 58, 180, 249, 82, 202, 193, 250, 153, 68, 25, 57, 231, 142, 167, 77, 107, 232, 29, 223, 112, 150, 232, 117, 19, 220, 97, 93];
var clientKey = [166, 15, 201, 35, 214, 126, 134, 68, 169, 45, 22, 185, 110, 218, 94, 244, 101, 107, 12, 114, 92, 72, 67, 116, 190, 37, 83, 85, 118, 153, 110, 139];
var storedKey = [88, 110, 93, 242, 131, 230, 220, 235, 92, 62, 121, 29, 139, 133, 40, 236, 25, 30, 102, 64, 69, 206, 151, 23, 146, 226, 230, 181, 187, 19, 226, 166];
var clientSignature = [210, 115, 18, 70, 124, 40, 164, 10, 138, 127, 5, 199, 60, 13, 227, 62, 179, 203, 251, 74, 131, 120, 59, 88, 20, 76, 241, 154, 198, 190, 27, 223];
// according to RFC7667
var signature = "dHzbZapWIk4jUhN+Ute9ytag9zjfMHgsqmmiz7AndVQ="
```

by the way I [ported saslprep to dart](https://github.com/konsultaner/saslprep-dart) from the js-lib to make the normalization.

**Comment by ecorm** [comment]
@konsultaner Sorry, I don't have a working SCRAM implementation to verify any test vectors. Crossbar is supposed to support SCRAM, so perhaps they have some test vectors?

**Comment by konsultaner** [comment]
@ecorm Thank you!
@oberstet can you help?

**Comment by meejah** [comment]
The tests we do have for the experimental SCRAM implementation in Autobahn and crossbar are here: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/test/test_auth.py

**Comment by konsultaner** [comment]
@meejah I added a test with my test vector given by the [RFC7677](https://tools.ietf.org/html/rfc7677) and I trapped into 2 issues.

1st the pbkdf2 wants a `salt` of type `byte` but in your argon example the passt value is a string.
2nd if I convert the salt to a byte the same way the [argon2 does it](https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/auth.py#L203). The vector fails. If i just use the `b'W22ZaJ0SNY7soEsUEjb6gQ=='` notation as [done in the helper tests](https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/test/test_auth.py#L75) it also fails.

```python
    def test_basic_pbkdf2(self):
        scram = auth.AuthScram(
            nonce='rOprNGfwEbeRWgbNEkqO',
            kdf='pbkdf2',
            salt=binascii.b2a_hex(b'1234567890abcdef').decode('ascii'),
            iterations=4096,
            password='pencil',
            authid='user',
        )
        scram._client_nonce = binascii.b2a_hex(b'rOprNGfwEbeRWgbNEkqO').decode('ascii')
        self.assertEqual(
            {'nonce': '724f70724e476677456265525767624e456b714f'},
            scram.authextra,
        )

        import base64
        challenge = types.Challenge('scram', {
            'nonce': 'rOprNGfwEbeRWgbNEkqO%hvYDpWUa2RaTCAfuxFIlj)hNlF\$k0',
            'kdf': 'pbkdf2',
            'salt': binascii.b2a_hex(b'W22ZaJ0SNY7soEsUEjb6gQ==').decode('ascii'),
            'iterations': 4096
        })
        reply = scram.on_challenge(Mock(), challenge)
        self.assertEqual(
            b'dHzbZapWIk4jUhN+Ute9ytag9zjfMHgsqmmiz7AndVQ=',
            reply,
        )

        authextra = dict(
            scram_server_signature=b'dHzbZapWIk4jUhN+Ute9ytag9zjfMHgsqmmiz7AndVQ=',
        )
        scram.on_welcome(Mock(), authextra)
```

would you have a minute to maybe find what I'm doing wrong here?

**Comment by konsultaner** [comment]
@meejah Thanks for your hint. I finally got it. My implementation can be found here: https://github.com/konsultaner/connectanum-dart/blob/master/lib/src/authentication/scram_authentication.dart
