### ISSUE TITLE
please add connectanum-dart as listed client implementation

### ISSUE THREAD

**Issue by konsultaner** [wamp-proto/wamp-proto#371]
@oberstet could you please add my open source implementation of WAMP in dart on https://wamp-proto.org/implementations.html ?

*Description*: 

A WAMP client implementation for the [dart language](https://dart.dev/) and [flutter](https://flutter.dev/) projects.

**Comment by om26er** [comment]
@konsultaner Could you please share the link to the project here as well.

**Comment by konsultaner** [comment]
sorry ... https://pub.dev/packages/connectanum

**Comment by oberstet** [comment]
pls PR to https://github.com/wamp-proto/wamp-proto/blob/master/docs/implementations.rst - merging that will auto-build and auto-deploy to the website
