### ISSUE TITLE
Move DNS to GitHub Pages

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#404]
This https://github.com/wamp-proto/wamp-proto/pull/403 PR has brought big improvements / revamp of the spec and web site build.

The building and deploy to GH pages works perfectly: https://github.com/wamp-proto/wamp-proto/actions

The deployment to AWS s3/cloudfront fails with "Unable to locate credentials". However, rather than fixing that (the creds or creds sourcing on GH), we should retire the AWS stuff altogether, and that requires pointing https://wamp-proto.org/ to GH pages.

I can reconfigure the DNS for that, just need to know what it needs to be. Currently, the DNS setup configures custom DNS servers pointing to AWS name servers, but the DNS hoster can also user providers name servers, and we can setup CNAMEs or what ..

What is the recommended best practice for using GH pages with custom domains?

**Comment by oberstet** [comment]
ok, reconfigured DNS along

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

now need to wait until 

```
dig wamp-proto.org +noall +answer -t A
dig wamp-proto.org +noall +answer -t AAAA
```

returns

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

and

```
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```

**Comment by oberstet** [comment]
@KSDaemon mmh, https://wamp-proto.org/ looks good, is it really the "new" site contents?

**Comment by KSDaemon** [comment]
> @KSDaemon mmh, https://wamp-proto.org/ looks good, is it really the "new" site contents?

Yeeeah! Seems so. As there is no gitter links — so its definitely a new one :) 

Great!

**Comment by KSDaemon** [comment]
> What is the recommended best practice for using GH pages with custom domains?

I don't find any special things related. So i think you've done it right! Just pointing to gh :)
