### ISSUE TITLE
Update Feature statuses

### ISSUE THREAD

**Issue by KSDaemon** [wamp-proto/wamp-proto#415]
Seems that we didn't update feature statuses for a long time in the spec.

But some features are described more in detail, and some are supported in most of the implementations. 

So I propose to update the statuses of the next features:
* Progressive CAll Results: `beta` → `stable`
* Pattern-based Registration: `beta` → `stable`
* Pattern-based Subscription: `beta` → `stable`
* Publisher Identification: `alpha` → `stable`
* Caller Identification: `alpha` → `stable`
* Progressive Calls: `sketch` → `beta`. As of now it has a clean definition in spec and can be implemented.
* Challenge-response Authentication: `beta` → `stable`

Of course, `stable` doesn't mean that it is frozen and we can not develop it more and add new options etc. It means that the current description of the feature is full and clean and has working and proven implementations.

I'll just remind you what statuses mean:

Status | Description
-- | --
sketch | There is a rough description of an itch to scratch, but the feature use case isn't clear, and there is no protocol proposal at all.
alpha | The feature use case is still fuzzy and/or the feature definition is unclear, but there is at least a protocol level proposal.
beta | The feature use case is clearly defined and the feature definition in the spec is sufficient to write a prototype implementation. The feature definition and details may still be incomplete and change.
stable | The feature definition in the spec is complete and stable and the feature use case is field proven in real applications. There are multiple, interoperable implementations.

Please write your thoughts on these changes! Or even propose an additional one!

**Comment by oberstet** [comment]
I'm +1 on this! just a few comments:

reading the status map, I think it is ok to jump Publisher and Caller Identification by 2 levels from alpha to stable. Mmmh, it probably should have been beta already.

rgd the status "beta": it doesn't say in the text, but actually this status was also thought of meaning there are at least 2 interoperable implementations.

if we would go with this criteria, then I would opt for "alpha" with the new "Progressive Calls" feature. I would also argue that it is very likely that we might need to get back to the drawing/design once we have different implementations, and also in particular once trying with _both_ "Progressive Calls" and "Progressive Calls Results" (aka full streaming).

**Comment by KSDaemon** [comment]
yeah, agree. Fixed!

**Comment by Jopie64** [comment]
Maybe not the correct issue to ask, but does the 'Progressive call' feature also support (progressive) responses when the progressive call is still ongoing? (When used in combination with progressive response of course)

Because in that case I can imagine it being used for flow control or back pressure when progressive responses are used for streaming.

**Comment by KSDaemon** [comment]
@Jopie64 Well yeah! These two features are not correlated with each other, but they can work and supplement each other! 
For example, when uploading a file you can have a progress indicator.
In spec i showed 2 flows: the last one is exactly with progressive call results in use

**Comment by KSDaemon** [comment]
Closing as its merged

**Comment by oberstet** [comment]
> Because in that case I can imagine it being used for flow control or back pressure when progressive responses are used for streaming.

Yeah, this will be interesting to explore! The PR adds the progress for the call initiator arguments, and combined with the existing progress for the downstream call result direction, this will then also allow to do both at the same time, essentially "full duplex streaming single remote procedure calls"

Now, once we explore that, I would also expect that we will explore how to do backpressure on such a streaming call. In both directions. And yeah, we have to see .. maybe we will need some additional attribute for details/options to make backpressure work .. but I wouldn't expect sth breaking the fundamental basic design of this progress stuff.

**Comment by KSDaemon** [comment]
agree!
