### ISSUE TITLE
Event History: retrieve all events

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#42]
When retrieving event history on a topic by calling `wamp.topic.history.last`, setting `limit == 0` should retrieve the complete event history (if the broker allows to do that and/or the history does not exceed a broker limit).

**Comment by konsultaner** [comment]
It would probably be nice to have a `wamp.topic.history.settings` to find out how far we can go back, and why. Routers may have an message limit others may limit the history to memory usage or not at all. This may depend on the topic.

> setting `limit == 0` should retrieve the complete event history

+1 this is how everyone would implement it.

**Comment by oberstet** [comment]
closing as implementation defined (event history, and more so advanced extension)
