### ISSUE TITLE
Error URI for "result too long"

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#422]
I'm finding myself in a situation in my WAMP client library where I need to send an `ERROR` instead of a `RESULT` message due to the latter not being to fit within the rawsocket maximum payload length. This would be in response to an `INVOCATION`.

Because the client library takes care of serializing the WAMP message, the user of the library can't reasonably know in advance if the resulting `RESULT` message would overflow the rawsocket maximum payload length.

In those situations, I want my library to automatically send back an `ERROR` message with an URI indicating that the RPC cannot be fulfilled, due the the result not being able to fit within the rawsocket payload.

There doesn't seem to be a suitable URI already existing in the spec. I propose something along the lines of `wamp.error.result_too_long`.

**Comment by oberstet** [comment]
In Autobahn there is https://github.com/crossbario/autobahn-python/blob/528f6a05c2091e67a7b1cf7d968901119ec924df/autobahn/wamp/exception.py#L111

**Comment by ecorm** [comment]
> In Autobahn there is

I have to use _something_ to report back the error, so I'll adopt `wamp.error.payload_size_exceeded` as well in the meantime.
