### ISSUE TITLE
Payload Passthru Mode with zero copy need a ppt_payload_size

### ISSUE THREAD

**Issue by konsultaner** [wamp-proto/wamp-proto#427]
According to the current protocol definition the payload of a ppt message may be send as binary data:

> This means that the payload is not to be modified by WAMP peers, nor serialized in any manner, and is delivered as-is from the originating peer.

This means that even when using a **JSON** serializer the payload may be pure binary. This also means that the data sent over raw sockets would need to be copied to the heap-space of the current process in order to send it to a receiving peer (caller/subscriber). It is impossible to prevent a heap-space copy, because there json has no field size definitions and if sent over raw sockets there is no web socket frame that might indicate the length. 

My router implementation uses a zero-copy mechanism to prevent heap-space allocations during the message routing process. For any router that uses zero-copy mechanism it is impossible to do so if no payload size is provided. It would be great if an optional payload size is provided to allow zero-copy for ppt-mode payloads.

Like this if the payload is 1024 bytes:

```json
[
    48,
    25471,
    {
        "ppt_scheme": "wamp",
        "ppt_serializer": "cbor",
        "ppt_cipher": "xsalsa20poly1305",
        "ppt_keyid": "GTtQ37XGJO2O4R8Dvx4AUo8pe61D9evIWpKGQAPdOh0=",
        "ppt_size": 1024
    },
    "com.myapp.secret_rpc_for_sensitive_data",
    [Payload|binary]
]
```

**Comment by KSDaemon** [comment]
Well... Seems reasonable... If we mark it as optional, because, not all clients may implement it and not all routers need it, then i think it is ok!

**Comment by oberstet** [comment]
the payload size is the length of the payload received. If a zero-copy WAMP message level is needed, WAMP-flatbuffers is almost done. "It would be great if an optional payload size is provided to allow zero-copy for ppt-mode payloads.": even if "ppt_size" were present in the map, you couldn't access "ppt_size" without parsing through the outer WAMP message - when not using WAMP-flatbuffers. With that, it would work ...

**Comment by oberstet** [comment]
ok, quick googling about the matter of union for java + uring ... seems to be a thing https://github.com/bbeaupain/nio_uring

however:

> Direct buffers - All ByteBuffer instances used with this library must be direct (e.g. allocated with allocateDirect). This is a hard requirement and is what enables zero-copy functionality.

**Comment by konsultaner** [comment]
Yes, I know there is also an [incubator project for netty](https://github.com/netty/netty-incubator-transport-io_uring), that uses uring.

**Comment by oberstet** [comment]
and it's using mmap under the hood https://github.com/netty/netty-incubator-transport-io_uring/blob/f959b71b99c3dbe5813450f7035767e9bf235019/transport-native-io_uring/src/main/c/netty_io_uring_native.c#L85

**Comment by konsultaner** [comment]
I went through my code again and saw that both websockets and rawsockets actually provide the final length already. So one can calculate the offsets by using the given lengths.

> Given a raw byte string B, how do you find the offset Off("ppt_size") within B and only parse that?

> Given that offset, how do you find the offset of Payload and ignore that (or find the offsets and parse whatever else you need)?

I wrote a WAMP specific stream serializer for that pupouse. Works like charm :)

> How do you do above by only relying on CBOR spec'ed formatting, and not an implementation detail of a specific CBOR parser? I haven't dug into the CBOR spec to that detail, but I am just wondering: wouldn't it rely on non-standard behavior?

Taking a fast look at the specs made me think it sould also work with cbor. It does work with msgpack :)
