### ISSUE TITLE
Define and discuss "global scope" in spec

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#429]
The spec uses the term "global scope"

https://wamp-proto.org/wamp_latest_ietf.html#name-ids

but there is no spec text defining or explaining the background.

**Comment by ecorm** [comment]
It's also not clear if IDs above "Session Scope" only need to be unique under a given realm, or if they need to be unique across a router hosting multiple realms.

Given "WAMP messages are only routed within a Realm" (https://wamp-proto.org/wamp_latest_ietf.html#section-1.3.1-1), shouldn't "Router Scope" be better named as "Realm Scope"?

**Comment by ecorm** [comment]
Is this issue a duplicate of #231, which is still open?

**Comment by KSDaemon** [comment]
Yeah! Seems for me too. Let's close and continue the discussion in #231 ?

**Comment by oberstet** [comment]
Ok, let's continue on #231
