### ISSUE TITLE
Consider renaming wamp.close.normal

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#462]
If it's not too late, I would like to discuss the rationale for the naming behind the `wamp.close.normal` error URI, used as default for the [wamp.session.kill](https://wamp-proto.org/wamp_latest_ietf.html#name-wampsessionkill) meta procedure.

From the point of view of the client, having one's session forcibly killed is certainly not "normal". I would suggest something like `wamp.close.killed` instead.

I apologize for missing this back then I reviewed PR #315.

**Comment by ecorm** [comment]
Pinging @oberstet , @gammazero , @KSDaemon , @johannwagner , @martin31821 who participated in the session meta API issue and PR.

**Comment by oberstet** [comment]
> From the point of view of the client, having one's session forcibly killed is certainly not "normal". I would suggest something like `wamp.close.killed` instead.

makes sense. tbh, I don't know if I actually noted that detail at the time of the PR ..

**Comment by ecorm** [comment]
> makes sense. tbh, I don't know if I actually noted that detail at the time of the PR ..

You requested that URI specifically in this comment: https://github.com/wamp-proto/wamp-proto/pull/315#issuecomment-400668075

I didn't object at the time (or I missed that comment), so I can't complain much now. :grin:

**Comment by KSDaemon** [comment]
I agree: for the killing session `wamp.close.killed` fits way better than `wamp.close.normal`

**Comment by ecorm** [comment]
Submitted PR #483
