### ISSUE TITLE
Add acknowledge option to CALL message?

### ISSUE THREAD

**Issue by SunFulong** [wamp-proto/wamp-proto#468]
Like PUBLISH message, could we add an acknowledge option to CALL message if the caller doesn't care the execute result?

**Comment by oberstet** [comment]
>  if the caller doesn't care the execute result?

what should that mean?

a CALL will be answered with RESULT or ERROR - eventually (when using call timeouts).

so there is no point in an acknowledge option

**Comment by SunFulong** [comment]
One procedure will be called from different clients, but some clients may be don't need the RESULT, so they can pass the {acknowledge: false} to let the router do not reply RESULTs.

**Comment by KSDaemon** [comment]
Well, @SunFulong let me explain: 

`acknowledge` means confirming the fact of some operation. PUBLISH affirms that the Event was published to the relevant topic(s) by the broker, and that it was not omitted or even loosed on the way. 

If you make a CALL to some procedure — it is stated that you will eventually receive a RESULT or an ERROR.
But that doesn't mean  the RESULT must be full of `args` and `kwargs` payload. It may be empty! BUT this will still be the RESULT message.

**Comment by oberstet** [comment]
> but some clients may be don't need the RESULT

so they can simply ignore a received RESULT

**Comment by KSDaemon** [comment]
Right: clients can ignore RESULT on their [client-code] side :) 
We're against this on the protocol level.

**Comment by SunFulong** [comment]
> so they can simply ignore a received RESULT

My intention is to allow CALLER to opt-in to tell the DEALER that they don't need the RESULT or ERROR, which saves some cost (such as AWS Serverless invoke/message/event cost).

**Comment by ecorm** [comment]
> My intention is to allow CALLER to opt-in to tell the DEALER that they don't need the RESULT or ERROR, which saves some cost (such as AWS Serverless invoke/message/event cost).

Could an unacknowledged `PUBLISH` from the client to the server work for you in this case? Instead of the back end registering a procedure, it would subscribe to a topic that the client publishes to. You can think of the topic as a "mailbox" for sending one-way "commands" from a client to the back end.

**Comment by SunFulong** [comment]
Could an unacknowledged PUBLISH from the client to the server work for you in this case?

Of course yes, but NOT every CALLER omit the RESULT, some did and some not, so I wanna a flag to tell the dealer NO NEED to reply, that maybe the natural way.

**Comment by ecorm** [comment]
> Of course yes, but NOT every CALLER omit the RESULT, some did and some not, so I wanna a flag to tell the dealer NO NEED to reply, that maybe the natural way.

You could make the clients who want the result use PUBLISH, and others use CALL. But I admit it could be a bit messy avoiding the code duplication in the corresponding EVENT and INVOCATION handlers.

I think your proposal is worth considering. I'm just trying to see if WAMP already has the features needed to accomplish your goal.

**Comment by SunFulong** [comment]
Current spec: In PubSub mode, "CALLER" may PUBLISH events, but WILL NOT acknowledge "no such registration". In RPC mode, the CALLER knows that there is a CALLEE that can handle the event, but will definitely receive an unneeded RESULT.

**Comment by ecorm** [comment]
> An extra flag can mark: just execute, don't tell me the result, but show me if no callee registered.

How should a client handle a `no_such_procedure` ERROR when it can no longer correlate it with the request ID of a "fire-and-forget" unacknowledged CALL?

**Comment by ecorm** [comment]
> How should a client handle a no_such_procedure ERROR when it can no longer correlate it with the request ID of a "fire-and-forget" unacknowledged CALL?

If a client can only expect to receive a possible negative acknowledge, but never expect to receive a positive acknowledgement, then time becomes the only way for a client to delete a pending call from its records.

Alternatively, a client library could allow the user to register a handler function for ERROR messages that don't correlate with any pending CALL requests. I don't know what the user could do with this information other than logging it, or perhaps aborting the program.

Neither of the above solutions are appealing to me, to be honest.

**Comment by SunFulong** [comment]
> How should a client handle a `no_such_procedure` ERROR when it can no longer correlate it with the request ID of a "fire-and-forget" unacknowledged CALL?

As spec, CALLER will receive ERROR if: A) no procedure registered to the Dealer, or B) the callee report an ERROR to the dealer.
the caller should receive A, but not receive B if unacknowledged marked.

**Comment by ecorm** [comment]
> As spec, CALLER will receive ERROR if: A) no procedure registered to the Dealer, or B) the callee report an ERROR to the dealer. the caller should receive A, but not receive B if unacknowledged marked.

I meant how should the client **implementation** (i.e. WAMP library) handle a received ERROR that it can no longer correlate with an unacknowledged `CALL` message? How do you expect a WAMP client implementation to behave in this circumstance, from an API standpoint?

**Comment by SunFulong** [comment]
> I meant how should the client implementation

Maybe a client global/default ERROR handler for the unack CALL?

**Comment by KSDaemon** [comment]
In my head the major difference between RPC and topics is exactly this:

* Topic — fire and forget (don't care about results, processing, etc)
* Rpc — get the result or error.

I understand @SunFulong case of possible savings. But still think that this is a fairly narrow case and not worth changing the protocol itself. 
Also, the adoption of such an option will require (significant) modifications on every side and also will rise a bunch of questions, like having `ack=false` router should not instantiate a call runtime object as it is expected not to receive any answer, right? But what if Callee ignores it and sends a YIELD? — Well router will treat it as an error. 

Having an empty response will clean up all the necessary runtime caches on every side, and it is not so big, just a few bytes:
```
[RESULT, CALL.Request|id, Details|dict] —> [50, 438093284, {}]
```
