### ISSUE TITLE
Unclear behavior for caller leaving during CALL request

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#477]
This is related to #476.

For **regular**, non-progressive calls, it's unclear how the router should react to the caller leaving in the middle of a CALL request, before the router receives a response from the callee.

Should the dealer send an INTERRUPT to the Callee if it supports call cancellation?

```mermaid
sequenceDiagram
    participant Caller
    participant Dealer
    participant Callee

    Caller->>Dealer: CALL
    Dealer->>Callee: INVOCATION
    Caller->>Dealer: GOODBYE
    Note right of Dealer: Should an INTERRUPT be sent to the  <br/>Callee if it supports call cancellation?
    Dealer->>Callee: INTERRUPT
```

The spec already mandates that the Dealer should send an INTERRUPT [in the case of progressive call results](https://wamp-proto.org/wamp_latest_ietf.html#section-11.1-55):

> Upon receiving a YIELD message from a _Callee_ with `YIELD.Options.progress == true` (for a call that is still ongoing), if the original _Caller_ is no longer available (has left the realm), then the _Dealer_ will send an INTERRUPT to the _Callee_. The INTERRUPT will have `Options.mode` set to `"killnowait"` to indicate to the client that no response should be sent to the INTERRUPT. This INTERRUPT is only sent in response to a progressive YIELD (`Details.progress == true`), **and is not sent in response to a normal or final YIELD**.

The above passage in bold is confusing, as INTERRUPTs are sent in response to a CANCEL, not YIELD. It also does not clearly specify what happens if the Dealer has not received any YIELD response yet.

For progressive call invocations, [the spec is much clearer](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-29):

> If the original _Caller_ is no longer available for some reason (has left the realm), then the _Dealer_ shall send an INTERRUPT to the _Callee_. The INTERRUPT MUST have `Options.mode` set to `"killnowait"` to indicate to the client that no response should be sent to the INTERRUPT.

I propose that behavior prescribed in progressive call invocations be applicable for _any_ type of CALL if the Callee supports call cancellation. For regular calls, if the Callee does not support cancellation, then the dealer simply discards the YIELD sent by the callee.

**Comment by KSDaemon** [comment]
> I propose that behavior prescribed in progressive call invocations be applicable for any type of CALL if the Callee supports call cancellation. For regular calls, if the Callee does not support cancellation, then the dealer simply discards the YIELD sent by the callee.

I totally agree with this.

**Comment by oberstet** [comment]
yes, I agree, the text for progressive calls is simpler and also clarifies the confusion you mention. maybe we can do even better?

> If the original Caller becomes unavailable for some reason (has left the realm), and an INVOCATION is still in progress, then the Dealer shall send an INTERRUPT to the Callee.

**Comment by ecorm** [comment]
>What about calls with progressive call arguments, but without progressive call results?
>
> Eg a Caller started sending progressive call arguments, but before sending a final argument (and hence the Callee could not yet have returned the bob-progressive result), the Caller disappear. Actually, I'm pretty sure the Router should send an INTERRUPT in that case as well?

The [Progressive Call Cancellation](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-29) subsection under the Progressive Call Invocations section does not mention anything about progressive results, so I think it's implied that an INTERRUPT must be sent regardless of the progressiveness of the results.

**Comment by oberstet** [comment]
> so I think it's implied  ...

yes, also think so. however, I'd argue in this case: we should improve the spec text by making stuff _explicit_ rather than rely on everyone associating the right implicit conclusion / transfer thought ...

**Comment by KSDaemon** [comment]
Yeah! +1. Let's describe the same approach explicitly in all related chapters: simple calls, progressive invocations & progressive results. This will result in a much cleaner and more understandable spec for external readers.

**Comment by ecorm** [comment]
> however, I'd argue in this case: we should improve the spec text by making stuff explicit rather than rely on everyone associating the right implicit conclusion / transfer thought ...

Agreed

> Yeah! +1. Let's describe the same approach explicitly in all related chapters: simple calls, progressive invocations & progressive results. This will result in a much cleaner and more understandable spec for external readers.

The Don't Repeat Yourself (DRY) principle applies to standards as much as it does to programming. That way you can't forget to synchronize changes in multiple places. Common behavior for all types of calls should be documented once under the basic profile. If we want to emphasize/clarify the behavior if the same for progressive calls, it should only be a citation to the appropriate subsection under the basic profile.

**Comment by KSDaemon** [comment]
@ecorm Yeah! Of course, you are right! I meant not to copy/paste but rather that we should make a notice in all other places to ref the original description. Sorry, I didn't state that clearly.
