### ISSUE TITLE
Propagation of frozen options in progressive call invocations

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#479]
According to the recently-added section [Freezing of Options in Progressive Call Invocations](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-74), the Dealer must apply the options of the initial CALL request to all subsequent INVOCATION messages of the same request. It then gives `disclose_me=true` as an example where all subsequent INVOCATION messages must contain the caller identity.

It also states:

>  Not having to repeat (and not being able to change) options is more in tune with the concept of a media stream where options are set up initially, and the source (Caller) only needs to keep uploading more data thereafter.

So this makes things more efficient for the Caller, but not for the Dealer and Callee which must still communicate these repeated options.

**I'm therefore wondering if the all options (except for `progress`) should be omitted on the Dealer->Callee leg as well in subsequent INVOCATION messages for the sake of efficiency.** This would transfer the burden of remembering the original options to the Callee.

My client implementation (CppWAMP) keeps records of active progressive invocation calls in memory, and it already stores the options of the original CALL.

I believe the only other WAMP implementation currently supporting progressive invocations is the one by @KSDaemon (Wampy.js?)

**Comment by ecorm** [comment]
> So in general, I think optimization is preferred: the dealer is one and potentially serves a huge number of clients, so reducing request memory footprint looks important.

Not just request memory, but there's an impact on network bandwidth as well.

**Comment by KSDaemon** [comment]
Right, network bandwidth too. 

The things that I'm worrying about are: what if Caller starts the progressive call with one option set and then suddenly sends a different option during intermediate calls? How this should be processed and on what side? Of course, it can be handled on the Callee side as a last resort :) And in case the Router doesn't store the options - it can only pass what it got further :)

But in some cases, it may be more attractive to catch that on the Router side... 
IDK. Just a thought out loud...

**Comment by ecorm** [comment]
> The things that I'm worrying about are: what if Caller starts the progressive call with one option set and then suddenly sends a different option during intermediate calls? How this should be processed and on what side? Of course, it can be handled on the Callee side as a last resort :) And in case the Router doesn't store the options - it can only pass what it got further :)

This is already covered [in the spec](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-59):

> Except for progress, items in the Options dictionary of the initiating progressive CALL shall be effective for the entirety of the progressive call request. Only the progress option shall be considered by the Dealer in subsequent progressive call invocations (within the same overall request). Except for progress, items in the Details dictionary of corresponding INVOCATION messages shall be based on the initiating progressive CALL only.

**Comment by oberstet** [comment]
> I'm therefore wondering if the all options (except for progress) should be omitted on the Dealer->Callee leg as well in subsequent INVOCATION messages for the sake of efficiency. 

that makes sense! not only for efficiency (save bytes on the wire), but also consistency, as when the options set in the initial message must be remembered by the Dealer/Callee, then there is no need to say what should happen if the Caller sends a different option value in a non-initial follow up message

looking at it from this angle, we should have a clear list of:

* the options which only can be set in the initial message
* the options which can be set on each message, including non-initial follow up messages

How do we call the first message? Is it the "first message of a WAMP _action_ (like for a call)"?

**Comment by ecorm** [comment]
> looking at it from this angle, we should have a clear list of:
>
>    - the options which only can be set in the initial message

All of them. There's already a list [here](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-74).

>    - the options which can be set on each message, including non-initial follow up messages

Only `progress`

>
> How do we call the first message? Is it the "first message of a WAMP action (like for a call)"?

The spec already uses "the initiating progressive CALL".

I'd like to put this issue to bed, and will propose a PR that mandates that options (except for `progress`) be not repeated in subsequent progressive calls, and that both the Dealer and Callee are responsible for remembering options from the initiating progressive call.
