### ISSUE TITLE
Error URI for expired progressive call race condition

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#482]
This is a continuation of the long discussion in #448, but will focus purely on the race conditions where a progressive CALL is made without the Caller knowing that the RPC is completed.

I can think of two scenarios where this can happen:
1. The callee left before the RPC was completed
2. The callee already returned an ERROR or a final RESULT

Here's a sequence diagram of the first scenario (where Network is used to simulate delay):

```mermaid
sequenceDiagram
    participant Caller
    participant Network
    participant Dealer
    participant Callee

    Caller->>Network: CALL (progress=true)
    Network->>Dealer: CALL (progress=true)
    Dealer->>Callee: INVOCATION
    Caller->>Network: CALL (progress=true)
    Callee->>Dealer: GOODBYE
    Dealer->>Network: ERROR (canceled) [1]
    Dealer->>Dealer: Delete call request record
    Network->>Caller: ERROR (canceled)
    Network->>Dealer: CALL (progress=true)
    Note right of Dealer: Call request ID not found
    Dealer->>Network: ERROR (which URI?)
    Network->>Caller: ERROR (which URI?)
```
[1] This behavior [is now mandated in the spec](https://wamp-proto.org/wamp_latest_ietf.html#name-callee-leaving-during-an-rp) as of PR #478 .

And here's a sequence diagram of the second scenario:

```mermaid
sequenceDiagram
    participant Caller
    participant Network
    participant Dealer
    participant Callee

    Caller->>Network: CALL (progress=true)
    Network->>Dealer: CALL (progress=true)
    Dealer->>Callee: INVOCATION
    Caller->>Network: CALL (progress=true)
    Callee->>Dealer: YIELD (progress=false)
    Dealer->>Network: RESULT (progress=false)
    Dealer->>Dealer: Delete call request record
    Network->>Caller: RESULT (progress=false)
    Network->>Dealer: CALL (progress=true)
    Note right of Dealer: Call request ID not found
    Dealer->>Network: ERROR (which URI?)
    Network->>Caller: ERROR (which URI?)
```

Both sequences are very similar. In both cases, the router receives a second progressive CALL with a request ID for which it cannot find a matching RPC in progress. It would be inappropriate to treat this as a protocol violation, because this is due to a race condition that is outside the control of the Caller.

**So I believe the question remains: what should be the error URI for these cases?**

There is `wamp.error.no_such_procedure`, but that would be a "lie". In the first scenario, the procedure could still be registered to another Callee via the shared registrations feature. In the second scenario, the procedure could still be registered to the same Callee.

I think that leaves `wamp.error.canceled` as the only viable candidate if we limit ourselves to existing error URIs. I think `wamp.error.canceled` would confusing in the second scenario, because the call was actually completed, not cancelled.

I therefore suggest: `wamp.error.no_such_call`. It would fit the theme for similarly-named URIs (e.g. `no_such_procedure`, `no_such_registration`, etc).

Another alternative would be not returning an ERROR at all, and ignore the second bogus CALL with no matching request ID. But I'm worried this could be lead to deadlock situations where a Caller is waiting forever for a response. I think it's better to return *something* and not leave the Caller waiting.

**Comment by Jopie64** [comment]
> Another alternative would be not returning an ERROR at all, and ignore the second bogus CALL with no matching request ID. But I'm worried this could be lead to deadlock situations where a Caller is waiting forever for a response. I think it's better to return something and not leave the Caller waiting.

If we define a new error because of possible deadlock, I think we really need to clarify how a deadlock can ever happen. And I currently don't see a way how a caller couldn't know about an ended CALL, even in case of races.

In fact, this new error would only be sent if a race actually occurred. Otherwise the caller would just receive a single canceled error. So if a deadlock could occur because of no error being sent in the case of a race, that same deadlock would still occur when there was no race.

The only reason I see why introducing an error like this might be good is that a caller can detect whether a progressive call has been processed or not. But then still I think there could be another race because of which that might still be unclear (a race to the callee), even when we do send a new error. (If you want I can clarify with diagram but I'm currently using my phone 😊)

So I currently don't see a good reason to introduce a new error and I would argue to keep it simple and just send nothing...

**Comment by ecorm** [comment]
> And I currently don't see a way how a caller couldn't know about an ended CALL, even in case of races.

I tried to think of such a situation and can't come up with any. The only possibility I can think of is if we allow the WAMP transport to be unreliable, which is currently not permitted by the spec (and I'm not saying it should be, either).

> So I currently don't see a good reason to introduce a new error and I would argue to keep it simple and just send nothing...

I now concur with this position after giving it some more thought. Thanks!

@oberstet and @KSDaemon (or anybody else): any thoughts?

**Comment by ecorm** [comment]
Submitted PR #491
