### ISSUE TITLE
Add `REGISTER.Options.forward_timeout` option

### ISSUE THREAD

**Issue by ecorm** [wamp-proto/wamp-proto#500]
Call timeouts can be executed in three places: the caller, the dealer, or the callee.

In the case of caller-initiated timeouts, there are no extra options added to CALL, and the caller handles the timeout logic itself, sending a CANCEL message if it wants to cancel the call when a timeout occurs.

In the case of dealer or callee-initiated timeouts, a `CALL.Options.timeout` option is added. The spec currently has this to say about which peer handles the timeout:

> The decision by *Dealers* to delegate timeouts to *Callees* supporting this feature MAY be determined by router configuration.

Instead of determining by router configuration (or in addition to the configuration), I propose that an option be added to REGISTER so that a callee may specify its desire to receive the `timeout` option and be responsible for handling timeouts. This would allow the Dealer's timeout forwarding decision to be more granular, that is, on a per-procedure basis (instead of all-or-nothing).

I'd be willing to write the PR for this proposed enhancement, but I first want to make sure the idea is supported.

**Comment by Jopie64** [comment]
Sounds good to me!
It also makes it more clear what you can expect from the router and what from the nodes. Less dependency on router configuration/implementation means less surprises means good 👍

**Comment by ecorm** [comment]
If anybody needs hints on how one can configure a Dealer to handle call forwarding, here's a snapshot of the enum I use as part of the CppWAMP router configuration:

```c++
//------------------------------------------------------------------------------
/** Determines how call timeouts are forwarded to callees. */
//------------------------------------------------------------------------------
enum class CallTimeoutForwardingRule
{
    perRegistration, /**< Forward if and only if the `forward_timeout` option
                          was set during procedure registration (default). */
    perFeature,      /**< Forward if and only if the callee announced support
                          for call timeouts under the `callee` role. */
    never            /**< Never forward call timeouts to callees and always
                          process them on the router. */
};
```

I suppose one could add an `always` option, but that could surprise callees that don't know anything about call timeouts.
