### ISSUE TITLE
What if session scope request id exceed maximum?

### ISSUE THREAD

**Issue by SunFulong** [wamp-proto/wamp-proto#521]
The spec defined session scope's request is an ID type, and range is from 1 to 2^53.

So, if a long-time session's request is exceed the maximum, what will client and router to do for next request? reset to 1?

**Comment by Jopie64** [comment]
Suppose a single request is on average 64 bytes. Suppose you have a dedicated high speed connection of 10Gb/s (+-1GB/s) fully allocated to only start requests. How long would it take for the counter to overflow? 

```
2^53 * 64 / 1024 / 1024 / 1024 / 3600s / 24h / 365d = 17y
```

Do we need to worry about it?

**Comment by Jopie64** [comment]
But now I'm thinking, that's what they reasoned about the IPv4 range, or 32 bit timestamps...

**Comment by SunFulong** [comment]
> Do we need to worry about it?

Although the number is large enough, but for a program, do self increase operation for a variable must process overflow behavior, the spec didn't define this yet, best solution is define the behavior instead leave to implementer.

**Comment by KSDaemon** [comment]
Actually, good question!
The first idea that got into my mind was the `half of the circle` approach. This is used for example by PostgreSQL.  

In a nutshell: the idea is to know the current id, treat the `id+2^53/2` as future Ids and `id-2^53/2` as previous IDs, having in mind that the next id after id=2^53 - is 1. 
Of course, everything is a bit complicated under the hood.

**Comment by SunFulong** [comment]
@KSDaemon I didn't get the mean of why `semi-circle`, but got the answer is `reset/wrapping to 1`, right?

**Comment by KSDaemon** [comment]
@SunFulong 
> but got the answer is reset/wrapping to 1, right?

well, as you correctly mentioned it is not defined in the spec) And you have an option: panic and abort your router or... Reset id (but be prepared for consequences)

**Comment by SunFulong** [comment]
@KSDaemon thanks for your detail explain.

In my implementation, I keep the `next request id` in `session` and when `new request` comes in, compare the `new request id` equal to current session `next request id` and then increment the session's `next request id`, so, I don't run into the problem you describe.

Until the spec defines the behavior, I'll assuming reset to 1 after overflow.

**Comment by meejah** [comment]
Crossbar/Autobahn does actually wrap, I believe (to `0` not `1`). See https://github.com/crossbario/autobahn-python/pull/420

It in fact used to randomly assign them, but (fun story!) there was an obscure bug filed that "under load" sometimes the router spit out spurious collision errors.

Turned out this was because indeed at "high capacity" and due to the Birthday Paradox JS's limit of 2^53 is insufficient and collisions become "fairly" likely, so it doesn't take very many seconds to see a collision.

**Comment by SunFulong** [comment]
> Crossbar/Autobahn does actually wrap, I believe (to 0 not 1)

@meejah Why is it 0? The current spec says that 0 is not a valid ID, and my implementation strictly treats a message with an ID of 0 as a MALFORMED message and will ABORT the session.

**Comment by meejah** [comment]
Not sure, https://github.com/wamp-proto/wamp-proto/blob/23337b357e6cad42b390822adb023f987ff90f20/rfc/text/basic/bp_02_building_blocks.md?plain=1#L100 definitely says "start at 1" but the code does start at 0 :thinking:

**Comment by oberstet** [comment]
> best solution is define the behavior instead leave to implementer.



https://github.com/crossbario/crossbar/blob/0089c1ef6fbbb87fc7316088a91f1859fa84eeb0/crossbar/router/session.py#L458

**Comment by SunFulong** [comment]
@oberstet Didn't get your mean, do you mean the initial request ID? I'm asking how the ID overflowed

**Comment by oberstet** [comment]
> @oberstet Didn't get your mean, do you mean the initial request ID? I'm asking how the ID overflowed

sorry, I just fat finger clicked submit too early;) pls see above ..

**Comment by SunFulong** [comment]
> A: session scope IDs correctly wrap around to 1

Should we write this rule into spec?

**Comment by oberstet** [comment]
Yes, I think it would be an improvement to make this _explicit_ in the text. Currently, it is only _implicit_ (by logic from the premises and constraints)

**Comment by meejah** [comment]
> He is also right about the issues with "randomly generated IDs" collisions and birthday paradox - BUT: I think this was in the context of session scope IDs not global scope IDs !

Yes, this was in session-scoped IDs.

I think 2^64 would be "enough" for random IDs, but also it has been a while (you'd need a _LOT_ of outstanding requests to start hitting collisions, in any case). Also, sequential seems fine although you do leak a little extra information to clients -- i.e. how much load / how many other clients there might be.

**Comment by oberstet** [comment]
> Also, sequential seems fine.

yes, I also think sequential (for session scope) is good.

but yes, it will leak some information ("how much load / how many other clients there might be.")

BUT: the leak of information should be restricted _per realm_ - thus: do we actually use session scoped _per realm_ in Crossbar.io? I forgot .. need to check ..

finally: "leak" .. for _what_ information? and what is the _unit_ of protection?

I would argue it is not "all sessions vs all sessions in realm R" or even "one given pair of session vs all other sessions in a given realm R"

for example, do we even want (independent of can we):

"Hide the total number of sessions in realm R from any one specific session in R?"

**Comment by oberstet** [comment]
Actually, we don't have "realm scope" at all. We only have:

* **global** scope 
* **router** scope 
* **session** scope

And the WAMP session IDs are global scope, while e.g. a (client initiated) `CALL` will get `CALL.Request|id`  assigned by the caller session (client) and from *session* scope

https://github.com/crossbario/autobahn-python/blob/924604ed250b565bcd17a30c101a86c67864811e/autobahn/wamp/message.py#L3933

**Comment by oberstet** [comment]
fixed via https://github.com/wamp-proto/wamp-proto/pull/522

**Comment by meejah** [comment]
> but yes, it will leak some information ("how much load / how many other clients there might be.")

Sorry for the confusion, I edited that out right after I posted because it's not a valid concern here (as you note). Since it's "session-scoped' IDs all it learns is how many requests _it_ has outstanding (which of course this client already knows).
