### ISSUE TITLE
"Advanced Transports and Serializers" Section Missing

### ISSUE THREAD

**Issue by om26er** [wamp-proto/wamp-proto#528]
In the deployed version of the spec the [Advanced Transports and Serializers](https://wamp-proto.org/wamp_ap_latest_ietf.html#name-advanced-transports-and-ser) is Missing.

The "section" exists on the sidebar but all its data is missing.

**Comment by oberstet** [comment]
not sure  - what do you mean? I can see the following - which seems correct?

![grafik](https://github.com/wamp-proto/wamp-proto/assets/233340/d09a84ff-a44a-403d-aa84-73f5e84395a0)

**Comment by KSDaemon** [comment]
Yeah, I just checked out — I see the same as @oberstet. Sidebar menu is ok and links are pointing correctly.

**Comment by om26er** [comment]
It works for me now as well. But I am very confident that section was missing content. In both "full" version and "advanced" profile

**Comment by oberstet** [comment]
> It is indeed happening on one of my computers, not really sure. It doesn't happen in Incognito, so I assume its some cache?

Maybe. Try clearing the cache when using non-ingonito? Who knows. It's "the web";) Bisect it: by host, uplink, browser type, browser instance, browser login/user, ..
