### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#61]
https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#reflection 
https://helloreverb.com/developers/swagger

**Comment by oberstet** [comment]
from the Hybi list, pointing out some unclear/missing aspects:

```
> Sometimes, the spec is misleading. E.g.:
> 
> 
>         13.3.12
>         <https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-13.3.12>.
>         Procedure Reflection also talks about topic reflection.
> 
> 
>         or
> 
> 
>         wamp.reflection.topic.list- where is the list coming from? How are topics persisted? Or
>         does it list only those previously defined? - Actually why not,
>         maybe that's where my "topic registration is"?
> 
>           or
> 
>         wamp.reflection.topic.describeand wamp.reflect.describe- what is the difference between the two?
> 
>         wamp.reflect.define- how do I specify if I want to define procedure or topic? Or
>         should the information be stored in the definition itself?
```

and **two use cases**:

``` 
>         The meta api and reflection is a very important aspect of a good SOA gateway/router/hub.
> 
>         It is important for me because (as specs points out):
> 
>           o  documentation
> 
>             o  discoverability (what applications are registered, what functionalities they offer)
> 
>             o  generating stubs and proxies (for Qt objects, generic UI for procedures and events)
```

**Comment by Paranaix** [comment]
I want to point out that one should also consider authorization in regards to this feature. Some metainformation maybe must not be available to every peer but only to some specific ones with a high enough clearance. E.g in a classic frontend-backend scenario, metainformations about backend services shall only be available to other backend services but not to regular users.

**Comment by oberstet** [comment]
Authorization is router specific (an implementation detail). This is mentioned in the spec. Crossbar.io will allow you to control authorization to WAMP meta API using it's built in authorization mechanisms.

**Comment by Paranaix** [comment]
Yeah but while designing this feature we have to make sure that there are ways how one can possibly configure authorization regarding this feature.

I don't think you have explicitely mentioned it in this issue here, but are there supossed to be a set of general procedures **and** a set of uris with the topic embedded in the uri itself? The latter would provide sufficient means to realize authorization.

**Comment by samson84** [comment]
Hi, I have created a topic in the OpenAPI community also related to the PUBSUB and RPC communication model documentation. See above.

It could be so good that this issue can be solved somehow. If there is anything that I can help you, please let me know.

**Comment by oberstet** [comment]
https://zelingher.wordpress.com/tag/wampsharp/

**Comment by oberstet** [comment]
Quoting:

> I made the TypedAutobahn repository public not long ago. You can find it on GitHub.
> There are a few things that are missing: regarding features, there is currently no support for publisher role.
> Regarding other stuff: some work on deployment needs to be done: the project currently targets Node (since it uses export/import syntax). A build that creates a version that is browser-friendly should be set. Also, a package for npm/bower/NuGet should be created and published automatically on builds.
> I should probably open GitHub issues regarding these. Any help on these or on anything else would be appreciated!

**Comment by oberstet** [comment]
Besides Swagger, in the REST world, there is RAML http://raml.org/

**Comment by oberstet** [comment]
http://elad.zelingher.com/blog/2016/06/19/Introducing%20TypedAutobahn/

**Comment by oberstet** [comment]
closing as implementation defined. eg crossbarfx has a tracing API (that _partially_ relates to this), and it has upcoming support for schema-based strong typing (via flatbuffers).
