### ISSUE TITLE
FAQ: WAMP vs other protocols

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#7]
FAQ: Describe how WAMP differs from
- MQTT
- AMQP
- STOMP
- 0MQ
- JAMP (http://json-amp.github.com/)
- complexity (for implementors, for users)
- Web'iness (browser compat. / WebSocket, use of URIs, ..)
## Some Links
- MQTT
  - http://blogs.vmware.com/vfabric/2013/02/choosing-your-messaging-protocol-amqp-mqtt-or-stomp.html
  - http://www.infoq.com/articles/interview-andy-piper
  - http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html
  - http://www.readwriteweb.com/hack/2011/11/ibms-andy-piper-part-3-the-tax.php
  - http://en.wikipedia.org/wiki/Mqtt
  - http://andypiper.co.uk/2011/11/04/mqtt-goes-free-a-personal-qa/
## Some Quotes

> There is space for a range of protocols to coexist, because they address different areas. In the messaging space, we’ve found over time that > whilst efforts to create a single protocol have been made, that has often ended up as focused around a particular set of qualities of service, and not optimised to cover the the whole range of them.
> For example, if we look at IBM’s own messaging protocols – there are several. There’s WebSphere MQ which is all about reliable, transactional, solid, clusterable, enterprise, JMS and other APIs, etc etc.. WMQ itself isn’t ideal for very high-speed in-memory or multicast scenarios, so there is also WMQ Low Latency (interoperable with the new multicast feature in WMQ 7.1, but a separate protocol). Neither WMQ LLM or WMQ scales down to unreliable device networks and embedded systems, so there is WMQ Telemetry (aka MQTT), which was specifically designed for constrained devices and networks, and that can interoperate with the main queue manager, too. Oh, and sometimes you want to deal with files (WMQ File Transfer Edition), or access message data via HTTP (WMQ HTTP Bridge). You need to address a range of requirements in a messaging story.

**Comment by CMCDragonkai** [comment]
Nice whitepaper I skimmed it, will go into detail in the future.

**Comment by oberstet** [comment]
@CMCDragonkai pls leave comments here! I'd be interested. I've also skimmed over. I don't agree with some of the assessments and assertions.

**Comment by oberstet** [comment]
http://www.cse.wustl.edu/~jain/cse570-15/ftp/iot_prot/#transport compares a number of "session-level protocols" for IoT:

* MQTT
* AMQP
* CoAP
* XMPP
* DDS

**Comment by oberstet** [comment]
This one is quite good, comparing MQTT and CoAP https://eclipse.org/community/eclipse_newsletter/2014/february/article2.php

**Comment by tacman** [comment]
Here's a table with some interesting comparisons:

http://wamp-proto.org/compared/

It's biased toward WAMP, but worth a look nonetheless.

**Comment by oberstet** [comment]
migrated to https://github.com/wamp-proto/wamp-web/issues/15
