### ISSUE TITLE
Finalize pattern-based subscriptions/registrations spec

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#71]

**Comment by KSDaemon** [comment]
Hi! Don't you think that in wildcard type of pattern-based subscription adding “star-mark” would be more clear for end user? I mean: 
"server.network..status" is less readable then "server.network.*.status” 
Sorry, if this is not right place for this discussion.

**Comment by ecorm** [comment]
In this sentence:

> When a single call matches more than one of a _Callees_ registrations, the call MAY be routed for invocation on multiple registrations, depending on call settings.

It's not clear what you mean by "call settings". Do mean the `CALL.Options` dictionary, or settings on the router?

**Comment by KSDaemon** [comment]
Hi, @ecorm !
There is CALL.Options.runon | string := "all" or "any" or "partition" that specifies the call workflow.
You can read more about it in https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#distributed-registrations-and-calls

**Comment by oberstet** [comment]
also: https://github.com/tavendo/WAMP/issues/174

**Comment by goeddea** [comment]
Everything in this is either covered by other issues ("*" for wildcards), now covered in the spec, or too general to be of any use.
