### ISSUE TITLE
Metaevent for first subscribe / last unsubscribe

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#79]
Application might want to optimize their behavior depending on whether there is _any_ subscriber subscribed to a topic used by the application at all.

E.g. when no one is subscribed to T1, the app might chose to optimize away any publication to T1 (since there is no one to receive anyway).

```
wamp.metaevent.topic.on_first_subscribe
wamp.metaevent.topic.on_last_unsubscribe
```

**Comment by goeddea** [comment]
Is covered by the current wamp.subscription.on_create / wamp.subscription.on_delete
