### ISSUE TITLE
add "WAMP materials section" to the WAMP homepage

### ISSUE THREAD

**Issue by goeddea** [wamp-proto/wamp-proto#94]
- a FAQ section or page which gives links to additional resources, e.g. blog posts, presentations, videos, with a very brief summary of each resource

links to add here:

Konstantin Burkalev's presentation on WAMP:
http://blog.ksdaemon.ru/2014/09/para-slov-pro-wamp/
http://www.slideshare.net/KSDaemon/wamp-39147463
http://www.slideshare.net/KSDaemon/wamp-en-exported

Tavendo blog posts on WAMP and what it makes possible

links to demo apps using WAMP

**Comment by oberstet** [comment]
migrated to https://github.com/wamp-proto/wamp-web/issues/15
